// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v3.21.12
// source: v1/pagebroker.proto

package pagebroker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Failure_Code int32

const (
	// No failure code was supplied.
	Failure_UNSPECIFIED Failure_Code = 0
	// The request is malformed or unsupported. PageBroker did not mutate transaction state.
	Failure_INVALID_REQUEST Failure_Code = 1
	// The transaction is unknown or has reached the opposite terminal state.
	Failure_TRANSACTION_NOT_FOUND Failure_Code = 2
	// The transaction ID or checkpoint destination conflicts with an existing transaction or output.
	Failure_TRANSACTION_CONFLICT Failure_Code = 3
	// Tmpfs staging lacks space. PageBroker did not create staging for this request.
	Failure_INSUFFICIENT_STORAGE Failure_Code = 4
	// Storage I/O failed. The caller may Abort the transaction before retrying with a new transaction ID.
	Failure_STORAGE_ERROR Failure_Code = 5
	// An unexpected broker failure occurred. The caller may Abort the transaction before retrying.
	Failure_INTERNAL_ERROR Failure_Code = 6
	// Storage extensions use 20+ to avoid the CUDA workstream's failure codes.
	Failure_STORE_MISMATCH       Failure_Code = 20 // Descriptor/target names another configured store; no storage I/O.
	Failure_ACCESS_DENIED        Failure_Code = 21 // Authentication, authorization or decryption refused; not proof of absence.
	Failure_STORAGE_UNAVAILABLE  Failure_Code = 22 // Transient storage/transport failure after bounded retries.
	Failure_ARTIFACT_NOT_FOUND   Failure_Code = 23 // Authoritative absence of the requested publication.
	Failure_ARTIFACT_CORRUPT     Failure_Code = 24 // Invalid index, unsafe paths, missing indexed data or digest mismatch.
	Failure_UNSUPPORTED_ARTIFACT Failure_Code = 25 // No reader for the backend/version pair.
	Failure_OUTCOME_UNKNOWN      Failure_Code = 26 // Cannot establish publication outcome; never authorizes process replay.
	Failure_TRANSACTION_EXPIRED  Failure_Code = 27 // Fixed transaction deadline elapsed; no new storage operations.
)

// Enum value maps for Failure_Code.
var (
	Failure_Code_name = map[int32]string{
		0:  "UNSPECIFIED",
		1:  "INVALID_REQUEST",
		2:  "TRANSACTION_NOT_FOUND",
		3:  "TRANSACTION_CONFLICT",
		4:  "INSUFFICIENT_STORAGE",
		5:  "STORAGE_ERROR",
		6:  "INTERNAL_ERROR",
		20: "STORE_MISMATCH",
		21: "ACCESS_DENIED",
		22: "STORAGE_UNAVAILABLE",
		23: "ARTIFACT_NOT_FOUND",
		24: "ARTIFACT_CORRUPT",
		25: "UNSUPPORTED_ARTIFACT",
		26: "OUTCOME_UNKNOWN",
		27: "TRANSACTION_EXPIRED",
	}
	Failure_Code_value = map[string]int32{
		"UNSPECIFIED":           0,
		"INVALID_REQUEST":       1,
		"TRANSACTION_NOT_FOUND": 2,
		"TRANSACTION_CONFLICT":  3,
		"INSUFFICIENT_STORAGE":  4,
		"STORAGE_ERROR":         5,
		"INTERNAL_ERROR":        6,
		"STORE_MISMATCH":        20,
		"ACCESS_DENIED":         21,
		"STORAGE_UNAVAILABLE":   22,
		"ARTIFACT_NOT_FOUND":    23,
		"ARTIFACT_CORRUPT":      24,
		"UNSUPPORTED_ARTIFACT":  25,
		"OUTCOME_UNKNOWN":       26,
		"TRANSACTION_EXPIRED":   27,
	}
)

func (x Failure_Code) Enum() *Failure_Code {
	p := new(Failure_Code)
	*p = x
	return p
}

func (x Failure_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Failure_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_pagebroker_proto_enumTypes[0].Descriptor()
}

func (Failure_Code) Type() protoreflect.EnumType {
	return &file_v1_pagebroker_proto_enumTypes[0]
}

func (x Failure_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Failure_Code.Descriptor instead.
func (Failure_Code) EnumDescriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{20, 0}
}

type FilesystemStorage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directory     *string                `protobuf:"bytes,1,opt,name=directory,proto3,oneof" json:"directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemStorage) Reset() {
	*x = FilesystemStorage{}
	mi := &file_v1_pagebroker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemStorage) ProtoMessage() {}

func (x *FilesystemStorage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemStorage.ProtoReflect.Descriptor instead.
func (*FilesystemStorage) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{0}
}

func (x *FilesystemStorage) GetDirectory() string {
	if x != nil && x.Directory != nil {
		return *x.Directory
	}
	return ""
}

type StorageBackend struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requests require exactly one storage kind.
	//
	// Types that are valid to be assigned to Kind:
	//
	//	*StorageBackend_Filesystem
	Kind          isStorageBackend_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageBackend) Reset() {
	*x = StorageBackend{}
	mi := &file_v1_pagebroker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageBackend) ProtoMessage() {}

func (x *StorageBackend) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageBackend.ProtoReflect.Descriptor instead.
func (*StorageBackend) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{1}
}

func (x *StorageBackend) GetKind() isStorageBackend_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *StorageBackend) GetFilesystem() *FilesystemStorage {
	if x != nil {
		if x, ok := x.Kind.(*StorageBackend_Filesystem); ok {
			return x.Filesystem
		}
	}
	return nil
}

type isStorageBackend_Kind interface {
	isStorageBackend_Kind()
}

type StorageBackend_Filesystem struct {
	Filesystem *FilesystemStorage `protobuf:"bytes,1,opt,name=filesystem,proto3,oneof"`
}

func (*StorageBackend_Filesystem) isStorageBackend_Kind() {}

type PosixCopyIOEngine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PosixCopyIOEngine) Reset() {
	*x = PosixCopyIOEngine{}
	mi := &file_v1_pagebroker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PosixCopyIOEngine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosixCopyIOEngine) ProtoMessage() {}

func (x *PosixCopyIOEngine) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosixCopyIOEngine.ProtoReflect.Descriptor instead.
func (*PosixCopyIOEngine) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{2}
}

type IOEngine struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requests require exactly one I/O engine.
	//
	// Types that are valid to be assigned to Kind:
	//
	//	*IOEngine_PosixCopy
	Kind          isIOEngine_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IOEngine) Reset() {
	*x = IOEngine{}
	mi := &file_v1_pagebroker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IOEngine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOEngine) ProtoMessage() {}

func (x *IOEngine) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOEngine.ProtoReflect.Descriptor instead.
func (*IOEngine) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{3}
}

func (x *IOEngine) GetKind() isIOEngine_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *IOEngine) GetPosixCopy() *PosixCopyIOEngine {
	if x != nil {
		if x, ok := x.Kind.(*IOEngine_PosixCopy); ok {
			return x.PosixCopy
		}
	}
	return nil
}

type isIOEngine_Kind interface {
	isIOEngine_Kind()
}

type IOEngine_PosixCopy struct {
	PosixCopy *PosixCopyIOEngine `protobuf:"bytes,1,opt,name=posix_copy,json=posixCopy,proto3,oneof"`
}

func (*IOEngine_PosixCopy) isIOEngine_Kind() {}

// Logical identity before publication. Neither field is a filesystem path.
type ArtifactIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactUid   string                 `protobuf:"bytes,1,opt,name=artifact_uid,json=artifactUid,proto3" json:"artifact_uid,omitempty"`       // Owning PodSnapshotContent UID.
	ContainerName string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"` // Captured container within that content.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactIdentity) Reset() {
	*x = ArtifactIdentity{}
	mi := &file_v1_pagebroker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactIdentity) ProtoMessage() {}

func (x *ArtifactIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactIdentity.ProtoReflect.Descriptor instead.
func (*ArtifactIdentity) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{4}
}

func (x *ArtifactIdentity) GetArtifactUid() string {
	if x != nil {
		return x.ArtifactUid
	}
	return ""
}

func (x *ArtifactIdentity) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

// Selects the configured store and destination before capture begins.
type ArtifactTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"` // Must match the configured store before I/O.
	Artifact      *ArtifactIdentity      `protobuf:"bytes,2,opt,name=artifact,proto3" json:"artifact,omitempty"`              // Logical destination within that store.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactTarget) Reset() {
	*x = ArtifactTarget{}
	mi := &file_v1_pagebroker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactTarget) ProtoMessage() {}

func (x *ArtifactTarget) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactTarget.ProtoReflect.Descriptor instead.
func (*ArtifactTarget) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{5}
}

func (x *ArtifactTarget) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *ArtifactTarget) GetArtifact() *ArtifactIdentity {
	if x != nil {
		return x.Artifact
	}
	return nil
}

// Immutable publication descriptor, persisted by Snapshot after checkpoint Commit.
// Handles are opaque to callers; the configured backend and version select the reader.
type PublishedArtifact struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	StoreId               string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`                                             // Bind subsequent reads to the original store.
	ArtifactHandle        string                 `protobuf:"bytes,2,opt,name=artifact_handle,json=artifactHandle,proto3" json:"artifact_handle,omitempty"`                        // Backend locator; callers persist it unchanged.
	ArtifactFormatVersion string                 `protobuf:"bytes,3,opt,name=artifact_format_version,json=artifactFormatVersion,proto3" json:"artifact_format_version,omitempty"` // Select the configured backend's reader.
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PublishedArtifact) Reset() {
	*x = PublishedArtifact{}
	mi := &file_v1_pagebroker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishedArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishedArtifact) ProtoMessage() {}

func (x *PublishedArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishedArtifact.ProtoReflect.Descriptor instead.
func (*PublishedArtifact) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{6}
}

func (x *PublishedArtifact) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *PublishedArtifact) GetArtifactHandle() string {
	if x != nil {
		return x.ArtifactHandle
	}
	return ""
}

func (x *PublishedArtifact) GetArtifactFormatVersion() string {
	if x != nil {
		return x.ArtifactFormatVersion
	}
	return ""
}

type StagedRestoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Legacy filesystem selector; mutually exclusive with artifact.
	Source *StorageBackend `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Required for legacy source. Optional with artifact: absence uses the configured
	// engine; an explicit engine must support the bound store. It cannot select a store.
	IoEngine      *IOEngine          `protobuf:"bytes,2,opt,name=io_engine,json=ioEngine,proto3" json:"io_engine,omitempty"`
	Artifact      *PublishedArtifact `protobuf:"bytes,3,opt,name=artifact,proto3" json:"artifact,omitempty"` // Exact committed source; never substitute another publication.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StagedRestoreRequest) Reset() {
	*x = StagedRestoreRequest{}
	mi := &file_v1_pagebroker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StagedRestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StagedRestoreRequest) ProtoMessage() {}

func (x *StagedRestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StagedRestoreRequest.ProtoReflect.Descriptor instead.
func (*StagedRestoreRequest) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{7}
}

func (x *StagedRestoreRequest) GetSource() *StorageBackend {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *StagedRestoreRequest) GetIoEngine() *IOEngine {
	if x != nil {
		return x.IoEngine
	}
	return nil
}

func (x *StagedRestoreRequest) GetArtifact() *PublishedArtifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

// Allows a future GPU engine to read source data without a staging directory.
type DirectRestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *StorageBackend        `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	IoEngine      *IOEngine              `protobuf:"bytes,2,opt,name=io_engine,json=ioEngine,proto3" json:"io_engine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectRestoreRequest) Reset() {
	*x = DirectRestoreRequest{}
	mi := &file_v1_pagebroker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectRestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectRestoreRequest) ProtoMessage() {}

func (x *DirectRestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectRestoreRequest.ProtoReflect.Descriptor instead.
func (*DirectRestoreRequest) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{8}
}

func (x *DirectRestoreRequest) GetSource() *StorageBackend {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *DirectRestoreRequest) GetIoEngine() *IOEngine {
	if x != nil {
		return x.IoEngine
	}
	return nil
}

type PrepareStagedCheckpointRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Legacy filesystem selector; mutually exclusive with target.
	Destination *StorageBackend `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	// Required for legacy destination; optional with target (configured engine by default).
	IoEngine      *IOEngine       `protobuf:"bytes,2,opt,name=io_engine,json=ioEngine,proto3" json:"io_engine,omitempty"`
	Target        *ArtifactTarget `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"` // Validate the configured store and destination before capture.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareStagedCheckpointRequest) Reset() {
	*x = PrepareStagedCheckpointRequest{}
	mi := &file_v1_pagebroker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareStagedCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareStagedCheckpointRequest) ProtoMessage() {}

func (x *PrepareStagedCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareStagedCheckpointRequest.ProtoReflect.Descriptor instead.
func (*PrepareStagedCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{9}
}

func (x *PrepareStagedCheckpointRequest) GetDestination() *StorageBackend {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *PrepareStagedCheckpointRequest) GetIoEngine() *IOEngine {
	if x != nil {
		return x.IoEngine
	}
	return nil
}

func (x *PrepareStagedCheckpointRequest) GetTarget() *ArtifactTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

// Fetch verified manifest.yaml for this exact publication into private shared staging.
// Snapshot interprets the manifest. This does not verify all checkpoint payloads.
type GetArtifactMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *PublishedArtifact     `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactMetadataRequest) Reset() {
	*x = GetArtifactMetadataRequest{}
	mi := &file_v1_pagebroker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactMetadataRequest) ProtoMessage() {}

func (x *GetArtifactMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetArtifactMetadataRequest) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{10}
}

func (x *GetArtifactMetadataRequest) GetArtifact() *PublishedArtifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

// Completes a live transaction. PageBroker retains up to 1,024 terminal transactions for up to one hour.
// Repeating Commit returns the same retained result, including any PublishedArtifact.
// Commit for an aborted, expired, or unknown transaction returns TRANSACTION_NOT_FOUND.
type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_v1_pagebroker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{11}
}

// Releases PageBroker state for a live transaction. PageBroker retains up to 1,024 terminal transactions for up to
// one hour. Repeating Abort for a retained aborted transaction returns AbortComplete; Abort for a committed, expired,
// or unknown transaction returns TRANSACTION_NOT_FOUND.
type AbortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRequest) Reset() {
	*x = AbortRequest{}
	mi := &file_v1_pagebroker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRequest) ProtoMessage() {}

func (x *AbortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRequest.ProtoReflect.Descriptor instead.
func (*AbortRequest) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{12}
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Snapshot assigns an ID to each request.
	RequestId *string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
	// Snapshot assigns a unique transaction ID before the first request and never reuses it.
	// This is distinct from the deterministic commitID derived from the artifact target.
	// Retries never extend a transaction's lifetime.
	TransactionId *string `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3,oneof" json:"transaction_id,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*Request_StagedRestore
	//	*Request_PrepareStagedCheckpoint
	//	*Request_Commit
	//	*Request_Abort
	//	*Request_DirectRestore
	//	*Request_GetArtifactMetadata
	Command       isRequest_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_v1_pagebroker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{13}
}

func (x *Request) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

func (x *Request) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

func (x *Request) GetCommand() isRequest_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Request) GetStagedRestore() *StagedRestoreRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_StagedRestore); ok {
			return x.StagedRestore
		}
	}
	return nil
}

func (x *Request) GetPrepareStagedCheckpoint() *PrepareStagedCheckpointRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_PrepareStagedCheckpoint); ok {
			return x.PrepareStagedCheckpoint
		}
	}
	return nil
}

func (x *Request) GetCommit() *CommitRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_Commit); ok {
			return x.Commit
		}
	}
	return nil
}

func (x *Request) GetAbort() *AbortRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_Abort); ok {
			return x.Abort
		}
	}
	return nil
}

func (x *Request) GetDirectRestore() *DirectRestoreRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_DirectRestore); ok {
			return x.DirectRestore
		}
	}
	return nil
}

func (x *Request) GetGetArtifactMetadata() *GetArtifactMetadataRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_GetArtifactMetadata); ok {
			return x.GetArtifactMetadata
		}
	}
	return nil
}

type isRequest_Command interface {
	isRequest_Command()
}

type Request_StagedRestore struct {
	StagedRestore *StagedRestoreRequest `protobuf:"bytes,3,opt,name=staged_restore,json=stagedRestore,proto3,oneof"`
}

type Request_PrepareStagedCheckpoint struct {
	PrepareStagedCheckpoint *PrepareStagedCheckpointRequest `protobuf:"bytes,4,opt,name=prepare_staged_checkpoint,json=prepareStagedCheckpoint,proto3,oneof"`
}

type Request_Commit struct {
	Commit *CommitRequest `protobuf:"bytes,5,opt,name=commit,proto3,oneof"`
}

type Request_Abort struct {
	Abort *AbortRequest `protobuf:"bytes,6,opt,name=abort,proto3,oneof"`
}

type Request_DirectRestore struct {
	DirectRestore *DirectRestoreRequest `protobuf:"bytes,7,opt,name=direct_restore,json=directRestore,proto3,oneof"`
}

type Request_GetArtifactMetadata struct {
	// Storage extensions use 20+; 8-19 remain available to the separate CUDA workstream.
	GetArtifactMetadata *GetArtifactMetadataRequest `protobuf:"bytes,20,opt,name=get_artifact_metadata,json=getArtifactMetadata,proto3,oneof"`
}

func (*Request_StagedRestore) isRequest_Command() {}

func (*Request_PrepareStagedCheckpoint) isRequest_Command() {}

func (*Request_Commit) isRequest_Command() {}

func (*Request_Abort) isRequest_Command() {}

func (*Request_DirectRestore) isRequest_Command() {}

func (*Request_GetArtifactMetadata) isRequest_Command() {}

type StagedRestoreDirectory struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ImageDirectory *string                `protobuf:"bytes,1,opt,name=image_directory,json=imageDirectory,proto3,oneof" json:"image_directory,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StagedRestoreDirectory) Reset() {
	*x = StagedRestoreDirectory{}
	mi := &file_v1_pagebroker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StagedRestoreDirectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StagedRestoreDirectory) ProtoMessage() {}

func (x *StagedRestoreDirectory) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StagedRestoreDirectory.ProtoReflect.Descriptor instead.
func (*StagedRestoreDirectory) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{14}
}

func (x *StagedRestoreDirectory) GetImageDirectory() string {
	if x != nil && x.ImageDirectory != nil {
		return *x.ImageDirectory
	}
	return ""
}

type DirectRestoreReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectRestoreReady) Reset() {
	*x = DirectRestoreReady{}
	mi := &file_v1_pagebroker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectRestoreReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectRestoreReady) ProtoMessage() {}

func (x *DirectRestoreReady) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectRestoreReady.ProtoReflect.Descriptor instead.
func (*DirectRestoreReady) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{15}
}

type StagedCheckpointDirectory struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ImageDirectory *string                `protobuf:"bytes,1,opt,name=image_directory,json=imageDirectory,proto3,oneof" json:"image_directory,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StagedCheckpointDirectory) Reset() {
	*x = StagedCheckpointDirectory{}
	mi := &file_v1_pagebroker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StagedCheckpointDirectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StagedCheckpointDirectory) ProtoMessage() {}

func (x *StagedCheckpointDirectory) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StagedCheckpointDirectory.ProtoReflect.Descriptor instead.
func (*StagedCheckpointDirectory) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{16}
}

func (x *StagedCheckpointDirectory) GetImageDirectory() string {
	if x != nil && x.ImageDirectory != nil {
		return *x.ImageDirectory
	}
	return ""
}

type CommitComplete struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required for target-addressed checkpoints. Absent for legacy checkpoints and restore cleanup.
	PublishedArtifact *PublishedArtifact `protobuf:"bytes,1,opt,name=published_artifact,json=publishedArtifact,proto3" json:"published_artifact,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CommitComplete) Reset() {
	*x = CommitComplete{}
	mi := &file_v1_pagebroker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitComplete) ProtoMessage() {}

func (x *CommitComplete) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitComplete.ProtoReflect.Descriptor instead.
func (*CommitComplete) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{17}
}

func (x *CommitComplete) GetPublishedArtifact() *PublishedArtifact {
	if x != nil {
		return x.PublishedArtifact
	}
	return nil
}

type GetArtifactMetadataComplete struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute local directory, shared with Snapshot; valid until Abort or metadata transaction expiry.
	ManifestDirectory string `protobuf:"bytes,1,opt,name=manifest_directory,json=manifestDirectory,proto3" json:"manifest_directory,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetArtifactMetadataComplete) Reset() {
	*x = GetArtifactMetadataComplete{}
	mi := &file_v1_pagebroker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactMetadataComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactMetadataComplete) ProtoMessage() {}

func (x *GetArtifactMetadataComplete) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactMetadataComplete.ProtoReflect.Descriptor instead.
func (*GetArtifactMetadataComplete) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{18}
}

func (x *GetArtifactMetadataComplete) GetManifestDirectory() string {
	if x != nil {
		return x.ManifestDirectory
	}
	return ""
}

// Confirms only that PageBroker transaction state/content was released; it says nothing about the target
// process or CUDA state.
type AbortComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortComplete) Reset() {
	*x = AbortComplete{}
	mi := &file_v1_pagebroker_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortComplete) ProtoMessage() {}

func (x *AbortComplete) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortComplete.ProtoReflect.Descriptor instead.
func (*AbortComplete) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{19}
}

type Failure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *Failure_Code          `protobuf:"varint,1,opt,name=code,proto3,enum=snapshot.pagebroker.v1.Failure_Code,oneof" json:"code,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"` // New storage handlers: at most 1024 UTF-8 bytes, no credentials/SDK bodies.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_v1_pagebroker_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{20}
}

func (x *Failure) GetCode() Failure_Code {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return Failure_UNSPECIFIED
}

func (x *Failure) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     *string                `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
	TransactionId *string                `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3,oneof" json:"transaction_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*Response_StagedRestoreDirectory
	//	*Response_StagedCheckpointDirectory
	//	*Response_CommitComplete
	//	*Response_AbortComplete
	//	*Response_Failure
	//	*Response_DirectRestoreReady
	//	*Response_GetArtifactMetadataComplete
	Result        isResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_v1_pagebroker_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{21}
}

func (x *Response) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

func (x *Response) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

func (x *Response) GetResult() isResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Response) GetStagedRestoreDirectory() *StagedRestoreDirectory {
	if x != nil {
		if x, ok := x.Result.(*Response_StagedRestoreDirectory); ok {
			return x.StagedRestoreDirectory
		}
	}
	return nil
}

func (x *Response) GetStagedCheckpointDirectory() *StagedCheckpointDirectory {
	if x != nil {
		if x, ok := x.Result.(*Response_StagedCheckpointDirectory); ok {
			return x.StagedCheckpointDirectory
		}
	}
	return nil
}

func (x *Response) GetCommitComplete() *CommitComplete {
	if x != nil {
		if x, ok := x.Result.(*Response_CommitComplete); ok {
			return x.CommitComplete
		}
	}
	return nil
}

func (x *Response) GetAbortComplete() *AbortComplete {
	if x != nil {
		if x, ok := x.Result.(*Response_AbortComplete); ok {
			return x.AbortComplete
		}
	}
	return nil
}

func (x *Response) GetFailure() *Failure {
	if x != nil {
		if x, ok := x.Result.(*Response_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

func (x *Response) GetDirectRestoreReady() *DirectRestoreReady {
	if x != nil {
		if x, ok := x.Result.(*Response_DirectRestoreReady); ok {
			return x.DirectRestoreReady
		}
	}
	return nil
}

func (x *Response) GetGetArtifactMetadataComplete() *GetArtifactMetadataComplete {
	if x != nil {
		if x, ok := x.Result.(*Response_GetArtifactMetadataComplete); ok {
			return x.GetArtifactMetadataComplete
		}
	}
	return nil
}

type isResponse_Result interface {
	isResponse_Result()
}

type Response_StagedRestoreDirectory struct {
	StagedRestoreDirectory *StagedRestoreDirectory `protobuf:"bytes,3,opt,name=staged_restore_directory,json=stagedRestoreDirectory,proto3,oneof"`
}

type Response_StagedCheckpointDirectory struct {
	StagedCheckpointDirectory *StagedCheckpointDirectory `protobuf:"bytes,4,opt,name=staged_checkpoint_directory,json=stagedCheckpointDirectory,proto3,oneof"`
}

type Response_CommitComplete struct {
	CommitComplete *CommitComplete `protobuf:"bytes,5,opt,name=commit_complete,json=commitComplete,proto3,oneof"`
}

type Response_AbortComplete struct {
	AbortComplete *AbortComplete `protobuf:"bytes,6,opt,name=abort_complete,json=abortComplete,proto3,oneof"`
}

type Response_Failure struct {
	Failure *Failure `protobuf:"bytes,7,opt,name=failure,proto3,oneof"`
}

type Response_DirectRestoreReady struct {
	DirectRestoreReady *DirectRestoreReady `protobuf:"bytes,8,opt,name=direct_restore_ready,json=directRestoreReady,proto3,oneof"`
}

type Response_GetArtifactMetadataComplete struct {
	GetArtifactMetadataComplete *GetArtifactMetadataComplete `protobuf:"bytes,20,opt,name=get_artifact_metadata_complete,json=getArtifactMetadataComplete,proto3,oneof"`
}

func (*Response_StagedRestoreDirectory) isResponse_Result() {}

func (*Response_StagedCheckpointDirectory) isResponse_Result() {}

func (*Response_CommitComplete) isResponse_Result() {}

func (*Response_AbortComplete) isResponse_Result() {}

func (*Response_Failure) isResponse_Result() {}

func (*Response_DirectRestoreReady) isResponse_Result() {}

func (*Response_GetArtifactMetadataComplete) isResponse_Result() {}

var File_v1_pagebroker_proto protoreflect.FileDescriptor

const file_v1_pagebroker_proto_rawDesc = "" +
	"\n" +
	"\x13v1/pagebroker.proto\x12\x16snapshot.pagebroker.v1\"D\n" +
	"\x11FilesystemStorage\x12!\n" +
	"\tdirectory\x18\x01 \x01(\tH\x00R\tdirectory\x88\x01\x01B\f\n" +
	"\n" +
	"_directory\"e\n" +
	"\x0eStorageBackend\x12K\n" +
	"\n" +
	"filesystem\x18\x01 \x01(\v2).snapshot.pagebroker.v1.FilesystemStorageH\x00R\n" +
	"filesystemB\x06\n" +
	"\x04kind\"\x13\n" +
	"\x11PosixCopyIOEngine\"^\n" +
	"\bIOEngine\x12J\n" +
	"\n" +
	"posix_copy\x18\x01 \x01(\v2).snapshot.pagebroker.v1.PosixCopyIOEngineH\x00R\tposixCopyB\x06\n" +
	"\x04kind\"\\\n" +
	"\x10ArtifactIdentity\x12!\n" +
	"\fartifact_uid\x18\x01 \x01(\tR\vartifactUid\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\"q\n" +
	"\x0eArtifactTarget\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12D\n" +
	"\bartifact\x18\x02 \x01(\v2(.snapshot.pagebroker.v1.ArtifactIdentityR\bartifact\"\x8f\x01\n" +
	"\x11PublishedArtifact\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12'\n" +
	"\x0fartifact_handle\x18\x02 \x01(\tR\x0eartifactHandle\x126\n" +
	"\x17artifact_format_version\x18\x03 \x01(\tR\x15artifactFormatVersion\"\xdc\x01\n" +
	"\x14StagedRestoreRequest\x12>\n" +
	"\x06source\x18\x01 \x01(\v2&.snapshot.pagebroker.v1.StorageBackendR\x06source\x12=\n" +
	"\tio_engine\x18\x02 \x01(\v2 .snapshot.pagebroker.v1.IOEngineR\bioEngine\x12E\n" +
	"\bartifact\x18\x03 \x01(\v2).snapshot.pagebroker.v1.PublishedArtifactR\bartifact\"\x95\x01\n" +
	"\x14DirectRestoreRequest\x12>\n" +
	"\x06source\x18\x01 \x01(\v2&.snapshot.pagebroker.v1.StorageBackendR\x06source\x12=\n" +
	"\tio_engine\x18\x02 \x01(\v2 .snapshot.pagebroker.v1.IOEngineR\bioEngine\"\xe9\x01\n" +
	"\x1ePrepareStagedCheckpointRequest\x12H\n" +
	"\vdestination\x18\x01 \x01(\v2&.snapshot.pagebroker.v1.StorageBackendR\vdestination\x12=\n" +
	"\tio_engine\x18\x02 \x01(\v2 .snapshot.pagebroker.v1.IOEngineR\bioEngine\x12>\n" +
	"\x06target\x18\x03 \x01(\v2&.snapshot.pagebroker.v1.ArtifactTargetR\x06target\"c\n" +
	"\x1aGetArtifactMetadataRequest\x12E\n" +
	"\bartifact\x18\x01 \x01(\v2).snapshot.pagebroker.v1.PublishedArtifactR\bartifact\"\x0f\n" +
	"\rCommitRequest\"\x0e\n" +
	"\fAbortRequest\"\x93\x05\n" +
	"\aRequest\x12\"\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tH\x01R\trequestId\x88\x01\x01\x12*\n" +
	"\x0etransaction_id\x18\x02 \x01(\tH\x02R\rtransactionId\x88\x01\x01\x12U\n" +
	"\x0estaged_restore\x18\x03 \x01(\v2,.snapshot.pagebroker.v1.StagedRestoreRequestH\x00R\rstagedRestore\x12t\n" +
	"\x19prepare_staged_checkpoint\x18\x04 \x01(\v26.snapshot.pagebroker.v1.PrepareStagedCheckpointRequestH\x00R\x17prepareStagedCheckpoint\x12?\n" +
	"\x06commit\x18\x05 \x01(\v2%.snapshot.pagebroker.v1.CommitRequestH\x00R\x06commit\x12<\n" +
	"\x05abort\x18\x06 \x01(\v2$.snapshot.pagebroker.v1.AbortRequestH\x00R\x05abort\x12U\n" +
	"\x0edirect_restore\x18\a \x01(\v2,.snapshot.pagebroker.v1.DirectRestoreRequestH\x00R\rdirectRestore\x12h\n" +
	"\x15get_artifact_metadata\x18\x14 \x01(\v22.snapshot.pagebroker.v1.GetArtifactMetadataRequestH\x00R\x13getArtifactMetadataB\t\n" +
	"\acommandB\r\n" +
	"\v_request_idB\x11\n" +
	"\x0f_transaction_id\"Z\n" +
	"\x16StagedRestoreDirectory\x12,\n" +
	"\x0fimage_directory\x18\x01 \x01(\tH\x00R\x0eimageDirectory\x88\x01\x01B\x12\n" +
	"\x10_image_directory\"\x14\n" +
	"\x12DirectRestoreReady\"]\n" +
	"\x19StagedCheckpointDirectory\x12,\n" +
	"\x0fimage_directory\x18\x01 \x01(\tH\x00R\x0eimageDirectory\x88\x01\x01B\x12\n" +
	"\x10_image_directory\"j\n" +
	"\x0eCommitComplete\x12X\n" +
	"\x12published_artifact\x18\x01 \x01(\v2).snapshot.pagebroker.v1.PublishedArtifactR\x11publishedArtifact\"L\n" +
	"\x1bGetArtifactMetadataComplete\x12-\n" +
	"\x12manifest_directory\x18\x01 \x01(\tR\x11manifestDirectory\"\x0f\n" +
	"\rAbortComplete\"\xd7\x03\n" +
	"\aFailure\x12=\n" +
	"\x04code\x18\x01 \x01(\x0e2$.snapshot.pagebroker.v1.Failure.CodeH\x00R\x04code\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x01R\amessage\x88\x01\x01\"\xd8\x02\n" +
	"\x04Code\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fINVALID_REQUEST\x10\x01\x12\x19\n" +
	"\x15TRANSACTION_NOT_FOUND\x10\x02\x12\x18\n" +
	"\x14TRANSACTION_CONFLICT\x10\x03\x12\x18\n" +
	"\x14INSUFFICIENT_STORAGE\x10\x04\x12\x11\n" +
	"\rSTORAGE_ERROR\x10\x05\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\x06\x12\x12\n" +
	"\x0eSTORE_MISMATCH\x10\x14\x12\x11\n" +
	"\rACCESS_DENIED\x10\x15\x12\x17\n" +
	"\x13STORAGE_UNAVAILABLE\x10\x16\x12\x16\n" +
	"\x12ARTIFACT_NOT_FOUND\x10\x17\x12\x14\n" +
	"\x10ARTIFACT_CORRUPT\x10\x18\x12\x18\n" +
	"\x14UNSUPPORTED_ARTIFACT\x10\x19\x12\x13\n" +
	"\x0fOUTCOME_UNKNOWN\x10\x1a\x12\x17\n" +
	"\x13TRANSACTION_EXPIRED\x10\x1bB\a\n" +
	"\x05_codeB\n" +
	"\n" +
	"\b_message\"\xa3\x06\n" +
	"\bResponse\x12\"\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tH\x01R\trequestId\x88\x01\x01\x12*\n" +
	"\x0etransaction_id\x18\x02 \x01(\tH\x02R\rtransactionId\x88\x01\x01\x12j\n" +
	"\x18staged_restore_directory\x18\x03 \x01(\v2..snapshot.pagebroker.v1.StagedRestoreDirectoryH\x00R\x16stagedRestoreDirectory\x12s\n" +
	"\x1bstaged_checkpoint_directory\x18\x04 \x01(\v21.snapshot.pagebroker.v1.StagedCheckpointDirectoryH\x00R\x19stagedCheckpointDirectory\x12Q\n" +
	"\x0fcommit_complete\x18\x05 \x01(\v2&.snapshot.pagebroker.v1.CommitCompleteH\x00R\x0ecommitComplete\x12N\n" +
	"\x0eabort_complete\x18\x06 \x01(\v2%.snapshot.pagebroker.v1.AbortCompleteH\x00R\rabortComplete\x12;\n" +
	"\afailure\x18\a \x01(\v2\x1f.snapshot.pagebroker.v1.FailureH\x00R\afailure\x12^\n" +
	"\x14direct_restore_ready\x18\b \x01(\v2*.snapshot.pagebroker.v1.DirectRestoreReadyH\x00R\x12directRestoreReady\x12z\n" +
	"\x1eget_artifact_metadata_complete\x18\x14 \x01(\v23.snapshot.pagebroker.v1.GetArtifactMetadataCompleteH\x00R\x1bgetArtifactMetadataCompleteB\b\n" +
	"\x06resultB\r\n" +
	"\v_request_idB\x11\n" +
	"\x0f_transaction_idB9Z7github.com/ai-dynamo/snapshot/agent/internal/pagebrokerb\x06proto3"

var (
	file_v1_pagebroker_proto_rawDescOnce sync.Once
	file_v1_pagebroker_proto_rawDescData []byte
)

func file_v1_pagebroker_proto_rawDescGZIP() []byte {
	file_v1_pagebroker_proto_rawDescOnce.Do(func() {
		file_v1_pagebroker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_pagebroker_proto_rawDesc), len(file_v1_pagebroker_proto_rawDesc)))
	})
	return file_v1_pagebroker_proto_rawDescData
}

var file_v1_pagebroker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_pagebroker_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_v1_pagebroker_proto_goTypes = []any{
	(Failure_Code)(0),                      // 0: snapshot.pagebroker.v1.Failure.Code
	(*FilesystemStorage)(nil),              // 1: snapshot.pagebroker.v1.FilesystemStorage
	(*StorageBackend)(nil),                 // 2: snapshot.pagebroker.v1.StorageBackend
	(*PosixCopyIOEngine)(nil),              // 3: snapshot.pagebroker.v1.PosixCopyIOEngine
	(*IOEngine)(nil),                       // 4: snapshot.pagebroker.v1.IOEngine
	(*ArtifactIdentity)(nil),               // 5: snapshot.pagebroker.v1.ArtifactIdentity
	(*ArtifactTarget)(nil),                 // 6: snapshot.pagebroker.v1.ArtifactTarget
	(*PublishedArtifact)(nil),              // 7: snapshot.pagebroker.v1.PublishedArtifact
	(*StagedRestoreRequest)(nil),           // 8: snapshot.pagebroker.v1.StagedRestoreRequest
	(*DirectRestoreRequest)(nil),           // 9: snapshot.pagebroker.v1.DirectRestoreRequest
	(*PrepareStagedCheckpointRequest)(nil), // 10: snapshot.pagebroker.v1.PrepareStagedCheckpointRequest
	(*GetArtifactMetadataRequest)(nil),     // 11: snapshot.pagebroker.v1.GetArtifactMetadataRequest
	(*CommitRequest)(nil),                  // 12: snapshot.pagebroker.v1.CommitRequest
	(*AbortRequest)(nil),                   // 13: snapshot.pagebroker.v1.AbortRequest
	(*Request)(nil),                        // 14: snapshot.pagebroker.v1.Request
	(*StagedRestoreDirectory)(nil),         // 15: snapshot.pagebroker.v1.StagedRestoreDirectory
	(*DirectRestoreReady)(nil),             // 16: snapshot.pagebroker.v1.DirectRestoreReady
	(*StagedCheckpointDirectory)(nil),      // 17: snapshot.pagebroker.v1.StagedCheckpointDirectory
	(*CommitComplete)(nil),                 // 18: snapshot.pagebroker.v1.CommitComplete
	(*GetArtifactMetadataComplete)(nil),    // 19: snapshot.pagebroker.v1.GetArtifactMetadataComplete
	(*AbortComplete)(nil),                  // 20: snapshot.pagebroker.v1.AbortComplete
	(*Failure)(nil),                        // 21: snapshot.pagebroker.v1.Failure
	(*Response)(nil),                       // 22: snapshot.pagebroker.v1.Response
}
var file_v1_pagebroker_proto_depIdxs = []int32{
	1,  // 0: snapshot.pagebroker.v1.StorageBackend.filesystem:type_name -> snapshot.pagebroker.v1.FilesystemStorage
	3,  // 1: snapshot.pagebroker.v1.IOEngine.posix_copy:type_name -> snapshot.pagebroker.v1.PosixCopyIOEngine
	5,  // 2: snapshot.pagebroker.v1.ArtifactTarget.artifact:type_name -> snapshot.pagebroker.v1.ArtifactIdentity
	2,  // 3: snapshot.pagebroker.v1.StagedRestoreRequest.source:type_name -> snapshot.pagebroker.v1.StorageBackend
	4,  // 4: snapshot.pagebroker.v1.StagedRestoreRequest.io_engine:type_name -> snapshot.pagebroker.v1.IOEngine
	7,  // 5: snapshot.pagebroker.v1.StagedRestoreRequest.artifact:type_name -> snapshot.pagebroker.v1.PublishedArtifact
	2,  // 6: snapshot.pagebroker.v1.DirectRestoreRequest.source:type_name -> snapshot.pagebroker.v1.StorageBackend
	4,  // 7: snapshot.pagebroker.v1.DirectRestoreRequest.io_engine:type_name -> snapshot.pagebroker.v1.IOEngine
	2,  // 8: snapshot.pagebroker.v1.PrepareStagedCheckpointRequest.destination:type_name -> snapshot.pagebroker.v1.StorageBackend
	4,  // 9: snapshot.pagebroker.v1.PrepareStagedCheckpointRequest.io_engine:type_name -> snapshot.pagebroker.v1.IOEngine
	6,  // 10: snapshot.pagebroker.v1.PrepareStagedCheckpointRequest.target:type_name -> snapshot.pagebroker.v1.ArtifactTarget
	7,  // 11: snapshot.pagebroker.v1.GetArtifactMetadataRequest.artifact:type_name -> snapshot.pagebroker.v1.PublishedArtifact
	8,  // 12: snapshot.pagebroker.v1.Request.staged_restore:type_name -> snapshot.pagebroker.v1.StagedRestoreRequest
	10, // 13: snapshot.pagebroker.v1.Request.prepare_staged_checkpoint:type_name -> snapshot.pagebroker.v1.PrepareStagedCheckpointRequest
	12, // 14: snapshot.pagebroker.v1.Request.commit:type_name -> snapshot.pagebroker.v1.CommitRequest
	13, // 15: snapshot.pagebroker.v1.Request.abort:type_name -> snapshot.pagebroker.v1.AbortRequest
	9,  // 16: snapshot.pagebroker.v1.Request.direct_restore:type_name -> snapshot.pagebroker.v1.DirectRestoreRequest
	11, // 17: snapshot.pagebroker.v1.Request.get_artifact_metadata:type_name -> snapshot.pagebroker.v1.GetArtifactMetadataRequest
	7,  // 18: snapshot.pagebroker.v1.CommitComplete.published_artifact:type_name -> snapshot.pagebroker.v1.PublishedArtifact
	0,  // 19: snapshot.pagebroker.v1.Failure.code:type_name -> snapshot.pagebroker.v1.Failure.Code
	15, // 20: snapshot.pagebroker.v1.Response.staged_restore_directory:type_name -> snapshot.pagebroker.v1.StagedRestoreDirectory
	17, // 21: snapshot.pagebroker.v1.Response.staged_checkpoint_directory:type_name -> snapshot.pagebroker.v1.StagedCheckpointDirectory
	18, // 22: snapshot.pagebroker.v1.Response.commit_complete:type_name -> snapshot.pagebroker.v1.CommitComplete
	20, // 23: snapshot.pagebroker.v1.Response.abort_complete:type_name -> snapshot.pagebroker.v1.AbortComplete
	21, // 24: snapshot.pagebroker.v1.Response.failure:type_name -> snapshot.pagebroker.v1.Failure
	16, // 25: snapshot.pagebroker.v1.Response.direct_restore_ready:type_name -> snapshot.pagebroker.v1.DirectRestoreReady
	19, // 26: snapshot.pagebroker.v1.Response.get_artifact_metadata_complete:type_name -> snapshot.pagebroker.v1.GetArtifactMetadataComplete
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_v1_pagebroker_proto_init() }
func file_v1_pagebroker_proto_init() {
	if File_v1_pagebroker_proto != nil {
		return
	}
	file_v1_pagebroker_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_pagebroker_proto_msgTypes[1].OneofWrappers = []any{
		(*StorageBackend_Filesystem)(nil),
	}
	file_v1_pagebroker_proto_msgTypes[3].OneofWrappers = []any{
		(*IOEngine_PosixCopy)(nil),
	}
	file_v1_pagebroker_proto_msgTypes[13].OneofWrappers = []any{
		(*Request_StagedRestore)(nil),
		(*Request_PrepareStagedCheckpoint)(nil),
		(*Request_Commit)(nil),
		(*Request_Abort)(nil),
		(*Request_DirectRestore)(nil),
		(*Request_GetArtifactMetadata)(nil),
	}
	file_v1_pagebroker_proto_msgTypes[14].OneofWrappers = []any{}
	file_v1_pagebroker_proto_msgTypes[16].OneofWrappers = []any{}
	file_v1_pagebroker_proto_msgTypes[20].OneofWrappers = []any{}
	file_v1_pagebroker_proto_msgTypes[21].OneofWrappers = []any{
		(*Response_StagedRestoreDirectory)(nil),
		(*Response_StagedCheckpointDirectory)(nil),
		(*Response_CommitComplete)(nil),
		(*Response_AbortComplete)(nil),
		(*Response_Failure)(nil),
		(*Response_DirectRestoreReady)(nil),
		(*Response_GetArtifactMetadataComplete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_pagebroker_proto_rawDesc), len(file_v1_pagebroker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_pagebroker_proto_goTypes,
		DependencyIndexes: file_v1_pagebroker_proto_depIdxs,
		EnumInfos:         file_v1_pagebroker_proto_enumTypes,
		MessageInfos:      file_v1_pagebroker_proto_msgTypes,
	}.Build()
	File_v1_pagebroker_proto = out.File
	file_v1_pagebroker_proto_goTypes = nil
	file_v1_pagebroker_proto_depIdxs = nil
}
