// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v3.21.12
// source: v1/pagebroker.proto

package pagebroker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Failure_Code int32

const (
	// No failure code was supplied.
	Failure_UNSPECIFIED Failure_Code = 0
	// The request is invalid or unsupported. PageBroker did not change transaction state.
	Failure_INVALID_REQUEST Failure_Code = 1
	// The transaction is unknown or has reached the opposite terminal state.
	Failure_TRANSACTION_NOT_FOUND Failure_Code = 2
	// The transaction ID or checkpoint destination conflicts with an existing transaction or output.
	Failure_TRANSACTION_CONFLICT Failure_Code = 3
	// Tmpfs staging lacks space. PageBroker did not create staging for this request.
	Failure_INSUFFICIENT_STORAGE Failure_Code = 4
	// Storage I/O failed. The caller may Abort the transaction before retrying with a new transaction ID.
	Failure_STORAGE_ERROR Failure_Code = 5
	// The operation failed or was cancelled. Abort the transaction before retrying.
	Failure_INTERNAL_ERROR Failure_Code = 6
)

// Enum value maps for Failure_Code.
var (
	Failure_Code_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "INVALID_REQUEST",
		2: "TRANSACTION_NOT_FOUND",
		3: "TRANSACTION_CONFLICT",
		4: "INSUFFICIENT_STORAGE",
		5: "STORAGE_ERROR",
		6: "INTERNAL_ERROR",
	}
	Failure_Code_value = map[string]int32{
		"UNSPECIFIED":           0,
		"INVALID_REQUEST":       1,
		"TRANSACTION_NOT_FOUND": 2,
		"TRANSACTION_CONFLICT":  3,
		"INSUFFICIENT_STORAGE":  4,
		"STORAGE_ERROR":         5,
		"INTERNAL_ERROR":        6,
	}
)

func (x Failure_Code) Enum() *Failure_Code {
	p := new(Failure_Code)
	*p = x
	return p
}

func (x Failure_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Failure_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_pagebroker_proto_enumTypes[0].Descriptor()
}

func (Failure_Code) Type() protoreflect.EnumType {
	return &file_v1_pagebroker_proto_enumTypes[0]
}

func (x Failure_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Failure_Code.Descriptor instead.
func (Failure_Code) EnumDescriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{26, 0}
}

type FilesystemStorage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directory     *string                `protobuf:"bytes,1,opt,name=directory,proto3,oneof" json:"directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemStorage) Reset() {
	*x = FilesystemStorage{}
	mi := &file_v1_pagebroker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemStorage) ProtoMessage() {}

func (x *FilesystemStorage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemStorage.ProtoReflect.Descriptor instead.
func (*FilesystemStorage) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{0}
}

func (x *FilesystemStorage) GetDirectory() string {
	if x != nil && x.Directory != nil {
		return *x.Directory
	}
	return ""
}

type StorageBackend struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requests require exactly one storage kind.
	//
	// Types that are valid to be assigned to Kind:
	//
	//	*StorageBackend_Filesystem
	Kind          isStorageBackend_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageBackend) Reset() {
	*x = StorageBackend{}
	mi := &file_v1_pagebroker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageBackend) ProtoMessage() {}

func (x *StorageBackend) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageBackend.ProtoReflect.Descriptor instead.
func (*StorageBackend) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{1}
}

func (x *StorageBackend) GetKind() isStorageBackend_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *StorageBackend) GetFilesystem() *FilesystemStorage {
	if x != nil {
		if x, ok := x.Kind.(*StorageBackend_Filesystem); ok {
			return x.Filesystem
		}
	}
	return nil
}

type isStorageBackend_Kind interface {
	isStorageBackend_Kind()
}

type StorageBackend_Filesystem struct {
	Filesystem *FilesystemStorage `protobuf:"bytes,1,opt,name=filesystem,proto3,oneof"`
}

func (*StorageBackend_Filesystem) isStorageBackend_Kind() {}

type PosixCopyIOEngine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PosixCopyIOEngine) Reset() {
	*x = PosixCopyIOEngine{}
	mi := &file_v1_pagebroker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PosixCopyIOEngine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosixCopyIOEngine) ProtoMessage() {}

func (x *PosixCopyIOEngine) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosixCopyIOEngine.ProtoReflect.Descriptor instead.
func (*PosixCopyIOEngine) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{2}
}

type IOEngine struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requests require exactly one I/O engine.
	//
	// Types that are valid to be assigned to Kind:
	//
	//	*IOEngine_PosixCopy
	//	*IOEngine_Nixl
	Kind          isIOEngine_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IOEngine) Reset() {
	*x = IOEngine{}
	mi := &file_v1_pagebroker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IOEngine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOEngine) ProtoMessage() {}

func (x *IOEngine) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOEngine.ProtoReflect.Descriptor instead.
func (*IOEngine) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{3}
}

func (x *IOEngine) GetKind() isIOEngine_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *IOEngine) GetPosixCopy() *PosixCopyIOEngine {
	if x != nil {
		if x, ok := x.Kind.(*IOEngine_PosixCopy); ok {
			return x.PosixCopy
		}
	}
	return nil
}

func (x *IOEngine) GetNixl() *NixlIOEngine {
	if x != nil {
		if x, ok := x.Kind.(*IOEngine_Nixl); ok {
			return x.Nixl
		}
	}
	return nil
}

type isIOEngine_Kind interface {
	isIOEngine_Kind()
}

type IOEngine_PosixCopy struct {
	PosixCopy *PosixCopyIOEngine `protobuf:"bytes,1,opt,name=posix_copy,json=posixCopy,proto3,oneof"`
}

type IOEngine_Nixl struct {
	Nixl *NixlIOEngine `protobuf:"bytes,2,opt,name=nixl,proto3,oneof"`
}

func (*IOEngine_PosixCopy) isIOEngine_Kind() {}

func (*IOEngine_Nixl) isIOEngine_Kind() {}

type GpuDeviceMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceUuid    string                 `protobuf:"bytes,1,opt,name=source_uuid,json=sourceUuid,proto3" json:"source_uuid,omitempty"`
	TargetUuid    string                 `protobuf:"bytes,2,opt,name=target_uuid,json=targetUuid,proto3" json:"target_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpuDeviceMapping) Reset() {
	*x = GpuDeviceMapping{}
	mi := &file_v1_pagebroker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuDeviceMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuDeviceMapping) ProtoMessage() {}

func (x *GpuDeviceMapping) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuDeviceMapping.ProtoReflect.Descriptor instead.
func (*GpuDeviceMapping) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{4}
}

func (x *GpuDeviceMapping) GetSourceUuid() string {
	if x != nil {
		return x.SourceUuid
	}
	return ""
}

func (x *GpuDeviceMapping) GetTargetUuid() string {
	if x != nil {
		return x.TargetUuid
	}
	return ""
}

// GPU execution supplies host PIDs resolved by the agent and the full context.
// Artifact validation occurs when CheckpointGpu or RestoreGpu runs.
type GpuContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CapturedPids   []uint32               `protobuf:"varint,1,rep,packed,name=captured_pids,json=capturedPids,proto3" json:"captured_pids,omitempty"`
	VisibleDevices []string               `protobuf:"bytes,2,rep,name=visible_devices,json=visibleDevices,proto3" json:"visible_devices,omitempty"`
	DeviceMap      []*GpuDeviceMapping    `protobuf:"bytes,3,rep,name=device_map,json=deviceMap,proto3" json:"device_map,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GpuContext) Reset() {
	*x = GpuContext{}
	mi := &file_v1_pagebroker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuContext) ProtoMessage() {}

func (x *GpuContext) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuContext.ProtoReflect.Descriptor instead.
func (*GpuContext) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{5}
}

func (x *GpuContext) GetCapturedPids() []uint32 {
	if x != nil {
		return x.CapturedPids
	}
	return nil
}

func (x *GpuContext) GetVisibleDevices() []string {
	if x != nil {
		return x.VisibleDevices
	}
	return nil
}

func (x *GpuContext) GetDeviceMap() []*GpuDeviceMapping {
	if x != nil {
		return x.DeviceMap
	}
	return nil
}

type GpuTarget struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CapturedPid uint32                 `protobuf:"varint,1,opt,name=captured_pid,json=capturedPid,proto3" json:"captured_pid,omitempty"`
	// PID in the host PID namespace.
	TargetPid     uint32 `protobuf:"varint,2,opt,name=target_pid,json=targetPid,proto3" json:"target_pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpuTarget) Reset() {
	*x = GpuTarget{}
	mi := &file_v1_pagebroker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuTarget) ProtoMessage() {}

func (x *GpuTarget) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuTarget.ProtoReflect.Descriptor instead.
func (*GpuTarget) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{6}
}

func (x *GpuTarget) GetCapturedPid() uint32 {
	if x != nil {
		return x.CapturedPid
	}
	return 0
}

func (x *GpuTarget) GetTargetPid() uint32 {
	if x != nil {
		return x.TargetPid
	}
	return 0
}

// Targets must be nonempty, have unique captured and target PIDs, and match
// GpuContext.captured_pids. Invalid sets return INVALID_REQUEST without execution.
type CheckpointGpuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*GpuTarget           `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	Context       *GpuContext            `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointGpuRequest) Reset() {
	*x = CheckpointGpuRequest{}
	mi := &file_v1_pagebroker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointGpuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointGpuRequest) ProtoMessage() {}

func (x *CheckpointGpuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointGpuRequest.ProtoReflect.Descriptor instead.
func (*CheckpointGpuRequest) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{7}
}

func (x *CheckpointGpuRequest) GetTargets() []*GpuTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *CheckpointGpuRequest) GetContext() *GpuContext {
	if x != nil {
		return x.Context
	}
	return nil
}

// Uses the same target validation as CheckpointGpuRequest.
type RestoreGpuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*GpuTarget           `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	Context       *GpuContext            `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreGpuRequest) Reset() {
	*x = RestoreGpuRequest{}
	mi := &file_v1_pagebroker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreGpuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreGpuRequest) ProtoMessage() {}

func (x *RestoreGpuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreGpuRequest.ProtoReflect.Descriptor instead.
func (*RestoreGpuRequest) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{8}
}

func (x *RestoreGpuRequest) GetTargets() []*GpuTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *RestoreGpuRequest) GetContext() *GpuContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_v1_pagebroker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{9}
}

type StagedRestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *StorageBackend        `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	IoEngine      *IOEngine              `protobuf:"bytes,2,opt,name=io_engine,json=ioEngine,proto3" json:"io_engine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StagedRestoreRequest) Reset() {
	*x = StagedRestoreRequest{}
	mi := &file_v1_pagebroker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StagedRestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StagedRestoreRequest) ProtoMessage() {}

func (x *StagedRestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StagedRestoreRequest.ProtoReflect.Descriptor instead.
func (*StagedRestoreRequest) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{10}
}

func (x *StagedRestoreRequest) GetSource() *StorageBackend {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *StagedRestoreRequest) GetIoEngine() *IOEngine {
	if x != nil {
		return x.IoEngine
	}
	return nil
}

// Keeps the source open for direct reads. Does not create CPU staging files.
type DirectRestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *StorageBackend        `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	IoEngine      *IOEngine              `protobuf:"bytes,2,opt,name=io_engine,json=ioEngine,proto3" json:"io_engine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectRestoreRequest) Reset() {
	*x = DirectRestoreRequest{}
	mi := &file_v1_pagebroker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectRestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectRestoreRequest) ProtoMessage() {}

func (x *DirectRestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectRestoreRequest.ProtoReflect.Descriptor instead.
func (*DirectRestoreRequest) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{11}
}

func (x *DirectRestoreRequest) GetSource() *StorageBackend {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *DirectRestoreRequest) GetIoEngine() *IOEngine {
	if x != nil {
		return x.IoEngine
	}
	return nil
}

type PrepareStagedCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   *StorageBackend        `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	IoEngine      *IOEngine              `protobuf:"bytes,2,opt,name=io_engine,json=ioEngine,proto3" json:"io_engine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareStagedCheckpointRequest) Reset() {
	*x = PrepareStagedCheckpointRequest{}
	mi := &file_v1_pagebroker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareStagedCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareStagedCheckpointRequest) ProtoMessage() {}

func (x *PrepareStagedCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareStagedCheckpointRequest.ProtoReflect.Descriptor instead.
func (*PrepareStagedCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{12}
}

func (x *PrepareStagedCheckpointRequest) GetDestination() *StorageBackend {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *PrepareStagedCheckpointRequest) GetIoEngine() *IOEngine {
	if x != nil {
		return x.IoEngine
	}
	return nil
}

type PrepareDirectCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   *StorageBackend        `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	IoEngine      *IOEngine              `protobuf:"bytes,2,opt,name=io_engine,json=ioEngine,proto3" json:"io_engine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareDirectCheckpointRequest) Reset() {
	*x = PrepareDirectCheckpointRequest{}
	mi := &file_v1_pagebroker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareDirectCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareDirectCheckpointRequest) ProtoMessage() {}

func (x *PrepareDirectCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareDirectCheckpointRequest.ProtoReflect.Descriptor instead.
func (*PrepareDirectCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{13}
}

func (x *PrepareDirectCheckpointRequest) GetDestination() *StorageBackend {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *PrepareDirectCheckpointRequest) GetIoEngine() *IOEngine {
	if x != nil {
		return x.IoEngine
	}
	return nil
}

// Completes a live transaction. PageBroker retains up to 1,024 terminal transactions for up to one hour.
// Repeating Commit for a retained committed transaction returns CommitComplete.
// Aborted, expired, or unknown transactions return TRANSACTION_NOT_FOUND.
type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_v1_pagebroker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{14}
}

// Releases PageBroker state for a live transaction. PageBroker retains up to 1,024 terminal transactions for up to
// one hour. Repeating Abort for a retained aborted transaction returns AbortComplete. Abort for a committed or
// expired, or unknown transaction returns TRANSACTION_NOT_FOUND.
type AbortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRequest) Reset() {
	*x = AbortRequest{}
	mi := &file_v1_pagebroker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRequest) ProtoMessage() {}

func (x *AbortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRequest.ProtoReflect.Descriptor instead.
func (*AbortRequest) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{15}
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Snapshot assigns an ID to each request.
	RequestId *string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
	// Snapshot assigns a unique transaction ID before the first request and does not reuse it while PageBroker retains it.
	// After two hours and five minutes, the transaction expires. This cancels GPU
	// work. Expiry cleanup waits for active GPU transfers to stop.
	TransactionId *string `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3,oneof" json:"transaction_id,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*Request_StagedRestore
	//	*Request_PrepareStagedCheckpoint
	//	*Request_Commit
	//	*Request_Abort
	//	*Request_DirectRestore
	//	*Request_PrepareDirectCheckpoint
	//	*Request_CheckpointGpu
	//	*Request_RestoreGpu
	//	*Request_Capabilities
	Command       isRequest_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_v1_pagebroker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{16}
}

func (x *Request) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

func (x *Request) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

func (x *Request) GetCommand() isRequest_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Request) GetStagedRestore() *StagedRestoreRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_StagedRestore); ok {
			return x.StagedRestore
		}
	}
	return nil
}

func (x *Request) GetPrepareStagedCheckpoint() *PrepareStagedCheckpointRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_PrepareStagedCheckpoint); ok {
			return x.PrepareStagedCheckpoint
		}
	}
	return nil
}

func (x *Request) GetCommit() *CommitRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_Commit); ok {
			return x.Commit
		}
	}
	return nil
}

func (x *Request) GetAbort() *AbortRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_Abort); ok {
			return x.Abort
		}
	}
	return nil
}

func (x *Request) GetDirectRestore() *DirectRestoreRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_DirectRestore); ok {
			return x.DirectRestore
		}
	}
	return nil
}

func (x *Request) GetPrepareDirectCheckpoint() *PrepareDirectCheckpointRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_PrepareDirectCheckpoint); ok {
			return x.PrepareDirectCheckpoint
		}
	}
	return nil
}

func (x *Request) GetCheckpointGpu() *CheckpointGpuRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_CheckpointGpu); ok {
			return x.CheckpointGpu
		}
	}
	return nil
}

func (x *Request) GetRestoreGpu() *RestoreGpuRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_RestoreGpu); ok {
			return x.RestoreGpu
		}
	}
	return nil
}

func (x *Request) GetCapabilities() *CapabilitiesRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_Capabilities); ok {
			return x.Capabilities
		}
	}
	return nil
}

type isRequest_Command interface {
	isRequest_Command()
}

type Request_StagedRestore struct {
	StagedRestore *StagedRestoreRequest `protobuf:"bytes,3,opt,name=staged_restore,json=stagedRestore,proto3,oneof"`
}

type Request_PrepareStagedCheckpoint struct {
	PrepareStagedCheckpoint *PrepareStagedCheckpointRequest `protobuf:"bytes,4,opt,name=prepare_staged_checkpoint,json=prepareStagedCheckpoint,proto3,oneof"`
}

type Request_Commit struct {
	Commit *CommitRequest `protobuf:"bytes,5,opt,name=commit,proto3,oneof"`
}

type Request_Abort struct {
	Abort *AbortRequest `protobuf:"bytes,6,opt,name=abort,proto3,oneof"`
}

type Request_DirectRestore struct {
	DirectRestore *DirectRestoreRequest `protobuf:"bytes,7,opt,name=direct_restore,json=directRestore,proto3,oneof"`
}

type Request_PrepareDirectCheckpoint struct {
	PrepareDirectCheckpoint *PrepareDirectCheckpointRequest `protobuf:"bytes,8,opt,name=prepare_direct_checkpoint,json=prepareDirectCheckpoint,proto3,oneof"`
}

type Request_CheckpointGpu struct {
	CheckpointGpu *CheckpointGpuRequest `protobuf:"bytes,9,opt,name=checkpoint_gpu,json=checkpointGpu,proto3,oneof"`
}

type Request_RestoreGpu struct {
	RestoreGpu *RestoreGpuRequest `protobuf:"bytes,10,opt,name=restore_gpu,json=restoreGpu,proto3,oneof"`
}

type Request_Capabilities struct {
	Capabilities *CapabilitiesRequest `protobuf:"bytes,11,opt,name=capabilities,proto3,oneof"`
}

func (*Request_StagedRestore) isRequest_Command() {}

func (*Request_PrepareStagedCheckpoint) isRequest_Command() {}

func (*Request_Commit) isRequest_Command() {}

func (*Request_Abort) isRequest_Command() {}

func (*Request_DirectRestore) isRequest_Command() {}

func (*Request_PrepareDirectCheckpoint) isRequest_Command() {}

func (*Request_CheckpointGpu) isRequest_Command() {}

func (*Request_RestoreGpu) isRequest_Command() {}

func (*Request_Capabilities) isRequest_Command() {}

type StagedRestoreDirectory struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ImageDirectory *string                `protobuf:"bytes,1,opt,name=image_directory,json=imageDirectory,proto3,oneof" json:"image_directory,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StagedRestoreDirectory) Reset() {
	*x = StagedRestoreDirectory{}
	mi := &file_v1_pagebroker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StagedRestoreDirectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StagedRestoreDirectory) ProtoMessage() {}

func (x *StagedRestoreDirectory) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StagedRestoreDirectory.ProtoReflect.Descriptor instead.
func (*StagedRestoreDirectory) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{17}
}

func (x *StagedRestoreDirectory) GetImageDirectory() string {
	if x != nil && x.ImageDirectory != nil {
		return *x.ImageDirectory
	}
	return ""
}

type DirectRestoreReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectRestoreReady) Reset() {
	*x = DirectRestoreReady{}
	mi := &file_v1_pagebroker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectRestoreReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectRestoreReady) ProtoMessage() {}

func (x *DirectRestoreReady) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectRestoreReady.ProtoReflect.Descriptor instead.
func (*DirectRestoreReady) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{18}
}

type DirectCheckpointDirectory struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ImageDirectory *string                `protobuf:"bytes,1,opt,name=image_directory,json=imageDirectory,proto3,oneof" json:"image_directory,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DirectCheckpointDirectory) Reset() {
	*x = DirectCheckpointDirectory{}
	mi := &file_v1_pagebroker_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectCheckpointDirectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectCheckpointDirectory) ProtoMessage() {}

func (x *DirectCheckpointDirectory) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectCheckpointDirectory.ProtoReflect.Descriptor instead.
func (*DirectCheckpointDirectory) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{19}
}

func (x *DirectCheckpointDirectory) GetImageDirectory() string {
	if x != nil && x.ImageDirectory != nil {
		return *x.ImageDirectory
	}
	return ""
}

type Capabilities struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CustomStorageAvailable bool                   `protobuf:"varint,1,opt,name=custom_storage_available,json=customStorageAvailable,proto3" json:"custom_storage_available,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_v1_pagebroker_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{20}
}

func (x *Capabilities) GetCustomStorageAvailable() bool {
	if x != nil {
		return x.CustomStorageAvailable
	}
	return false
}

type GpuParticipantResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapturedPid   uint32                 `protobuf:"varint,1,opt,name=captured_pid,json=capturedPid,proto3" json:"captured_pid,omitempty"`
	Bytes         uint64                 `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpuParticipantResult) Reset() {
	*x = GpuParticipantResult{}
	mi := &file_v1_pagebroker_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuParticipantResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuParticipantResult) ProtoMessage() {}

func (x *GpuParticipantResult) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuParticipantResult.ProtoReflect.Descriptor instead.
func (*GpuParticipantResult) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{21}
}

func (x *GpuParticipantResult) GetCapturedPid() uint32 {
	if x != nil {
		return x.CapturedPid
	}
	return 0
}

func (x *GpuParticipantResult) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type GpuComplete struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Participants  []*GpuParticipantResult `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpuComplete) Reset() {
	*x = GpuComplete{}
	mi := &file_v1_pagebroker_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuComplete) ProtoMessage() {}

func (x *GpuComplete) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuComplete.ProtoReflect.Descriptor instead.
func (*GpuComplete) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{22}
}

func (x *GpuComplete) GetParticipants() []*GpuParticipantResult {
	if x != nil {
		return x.Participants
	}
	return nil
}

type StagedCheckpointDirectory struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ImageDirectory *string                `protobuf:"bytes,1,opt,name=image_directory,json=imageDirectory,proto3,oneof" json:"image_directory,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StagedCheckpointDirectory) Reset() {
	*x = StagedCheckpointDirectory{}
	mi := &file_v1_pagebroker_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StagedCheckpointDirectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StagedCheckpointDirectory) ProtoMessage() {}

func (x *StagedCheckpointDirectory) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StagedCheckpointDirectory.ProtoReflect.Descriptor instead.
func (*StagedCheckpointDirectory) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{23}
}

func (x *StagedCheckpointDirectory) GetImageDirectory() string {
	if x != nil && x.ImageDirectory != nil {
		return *x.ImageDirectory
	}
	return ""
}

type CommitComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitComplete) Reset() {
	*x = CommitComplete{}
	mi := &file_v1_pagebroker_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitComplete) ProtoMessage() {}

func (x *CommitComplete) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitComplete.ProtoReflect.Descriptor instead.
func (*CommitComplete) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{24}
}

// GPU work and cleanup have finished before transaction files are released.
// This does not stop a workload that has already restored successfully.
type AbortComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortComplete) Reset() {
	*x = AbortComplete{}
	mi := &file_v1_pagebroker_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortComplete) ProtoMessage() {}

func (x *AbortComplete) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortComplete.ProtoReflect.Descriptor instead.
func (*AbortComplete) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{25}
}

type Failure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *Failure_Code          `protobuf:"varint,1,opt,name=code,proto3,enum=snapshot.pagebroker.v1.Failure_Code,oneof" json:"code,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_v1_pagebroker_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{26}
}

func (x *Failure) GetCode() Failure_Code {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return Failure_UNSPECIFIED
}

func (x *Failure) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     *string                `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
	TransactionId *string                `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3,oneof" json:"transaction_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*Response_StagedRestoreDirectory
	//	*Response_StagedCheckpointDirectory
	//	*Response_CommitComplete
	//	*Response_AbortComplete
	//	*Response_Failure
	//	*Response_DirectRestoreReady
	//	*Response_DirectCheckpointDirectory
	//	*Response_GpuCheckpointComplete
	//	*Response_GpuRestoreComplete
	//	*Response_Capabilities
	Result        isResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_v1_pagebroker_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{27}
}

func (x *Response) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

func (x *Response) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

func (x *Response) GetResult() isResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Response) GetStagedRestoreDirectory() *StagedRestoreDirectory {
	if x != nil {
		if x, ok := x.Result.(*Response_StagedRestoreDirectory); ok {
			return x.StagedRestoreDirectory
		}
	}
	return nil
}

func (x *Response) GetStagedCheckpointDirectory() *StagedCheckpointDirectory {
	if x != nil {
		if x, ok := x.Result.(*Response_StagedCheckpointDirectory); ok {
			return x.StagedCheckpointDirectory
		}
	}
	return nil
}

func (x *Response) GetCommitComplete() *CommitComplete {
	if x != nil {
		if x, ok := x.Result.(*Response_CommitComplete); ok {
			return x.CommitComplete
		}
	}
	return nil
}

func (x *Response) GetAbortComplete() *AbortComplete {
	if x != nil {
		if x, ok := x.Result.(*Response_AbortComplete); ok {
			return x.AbortComplete
		}
	}
	return nil
}

func (x *Response) GetFailure() *Failure {
	if x != nil {
		if x, ok := x.Result.(*Response_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

func (x *Response) GetDirectRestoreReady() *DirectRestoreReady {
	if x != nil {
		if x, ok := x.Result.(*Response_DirectRestoreReady); ok {
			return x.DirectRestoreReady
		}
	}
	return nil
}

func (x *Response) GetDirectCheckpointDirectory() *DirectCheckpointDirectory {
	if x != nil {
		if x, ok := x.Result.(*Response_DirectCheckpointDirectory); ok {
			return x.DirectCheckpointDirectory
		}
	}
	return nil
}

func (x *Response) GetGpuCheckpointComplete() *GpuComplete {
	if x != nil {
		if x, ok := x.Result.(*Response_GpuCheckpointComplete); ok {
			return x.GpuCheckpointComplete
		}
	}
	return nil
}

func (x *Response) GetGpuRestoreComplete() *GpuComplete {
	if x != nil {
		if x, ok := x.Result.(*Response_GpuRestoreComplete); ok {
			return x.GpuRestoreComplete
		}
	}
	return nil
}

func (x *Response) GetCapabilities() *Capabilities {
	if x != nil {
		if x, ok := x.Result.(*Response_Capabilities); ok {
			return x.Capabilities
		}
	}
	return nil
}

type isResponse_Result interface {
	isResponse_Result()
}

type Response_StagedRestoreDirectory struct {
	StagedRestoreDirectory *StagedRestoreDirectory `protobuf:"bytes,3,opt,name=staged_restore_directory,json=stagedRestoreDirectory,proto3,oneof"`
}

type Response_StagedCheckpointDirectory struct {
	StagedCheckpointDirectory *StagedCheckpointDirectory `protobuf:"bytes,4,opt,name=staged_checkpoint_directory,json=stagedCheckpointDirectory,proto3,oneof"`
}

type Response_CommitComplete struct {
	CommitComplete *CommitComplete `protobuf:"bytes,5,opt,name=commit_complete,json=commitComplete,proto3,oneof"`
}

type Response_AbortComplete struct {
	AbortComplete *AbortComplete `protobuf:"bytes,6,opt,name=abort_complete,json=abortComplete,proto3,oneof"`
}

type Response_Failure struct {
	Failure *Failure `protobuf:"bytes,7,opt,name=failure,proto3,oneof"`
}

type Response_DirectRestoreReady struct {
	DirectRestoreReady *DirectRestoreReady `protobuf:"bytes,8,opt,name=direct_restore_ready,json=directRestoreReady,proto3,oneof"`
}

type Response_DirectCheckpointDirectory struct {
	DirectCheckpointDirectory *DirectCheckpointDirectory `protobuf:"bytes,9,opt,name=direct_checkpoint_directory,json=directCheckpointDirectory,proto3,oneof"`
}

type Response_GpuCheckpointComplete struct {
	GpuCheckpointComplete *GpuComplete `protobuf:"bytes,10,opt,name=gpu_checkpoint_complete,json=gpuCheckpointComplete,proto3,oneof"`
}

type Response_GpuRestoreComplete struct {
	GpuRestoreComplete *GpuComplete `protobuf:"bytes,11,opt,name=gpu_restore_complete,json=gpuRestoreComplete,proto3,oneof"`
}

type Response_Capabilities struct {
	Capabilities *Capabilities `protobuf:"bytes,12,opt,name=capabilities,proto3,oneof"`
}

func (*Response_StagedRestoreDirectory) isResponse_Result() {}

func (*Response_StagedCheckpointDirectory) isResponse_Result() {}

func (*Response_CommitComplete) isResponse_Result() {}

func (*Response_AbortComplete) isResponse_Result() {}

func (*Response_Failure) isResponse_Result() {}

func (*Response_DirectRestoreReady) isResponse_Result() {}

func (*Response_DirectCheckpointDirectory) isResponse_Result() {}

func (*Response_GpuCheckpointComplete) isResponse_Result() {}

func (*Response_GpuRestoreComplete) isResponse_Result() {}

func (*Response_Capabilities) isResponse_Result() {}

// Registered-buffer transfers. Directory staging is not implemented for NIXL.
type NixlIOEngine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NixlIOEngine) Reset() {
	*x = NixlIOEngine{}
	mi := &file_v1_pagebroker_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NixlIOEngine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NixlIOEngine) ProtoMessage() {}

func (x *NixlIOEngine) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pagebroker_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NixlIOEngine.ProtoReflect.Descriptor instead.
func (*NixlIOEngine) Descriptor() ([]byte, []int) {
	return file_v1_pagebroker_proto_rawDescGZIP(), []int{28}
}

var File_v1_pagebroker_proto protoreflect.FileDescriptor

const file_v1_pagebroker_proto_rawDesc = "" +
	"\n" +
	"\x13v1/pagebroker.proto\x12\x16snapshot.pagebroker.v1\"D\n" +
	"\x11FilesystemStorage\x12!\n" +
	"\tdirectory\x18\x01 \x01(\tH\x00R\tdirectory\x88\x01\x01B\f\n" +
	"\n" +
	"_directory\"e\n" +
	"\x0eStorageBackend\x12K\n" +
	"\n" +
	"filesystem\x18\x01 \x01(\v2).snapshot.pagebroker.v1.FilesystemStorageH\x00R\n" +
	"filesystemB\x06\n" +
	"\x04kind\"\x13\n" +
	"\x11PosixCopyIOEngine\"\x9a\x01\n" +
	"\bIOEngine\x12J\n" +
	"\n" +
	"posix_copy\x18\x01 \x01(\v2).snapshot.pagebroker.v1.PosixCopyIOEngineH\x00R\tposixCopy\x12:\n" +
	"\x04nixl\x18\x02 \x01(\v2$.snapshot.pagebroker.v1.NixlIOEngineH\x00R\x04nixlB\x06\n" +
	"\x04kind\"T\n" +
	"\x10GpuDeviceMapping\x12\x1f\n" +
	"\vsource_uuid\x18\x01 \x01(\tR\n" +
	"sourceUuid\x12\x1f\n" +
	"\vtarget_uuid\x18\x02 \x01(\tR\n" +
	"targetUuid\"\xa3\x01\n" +
	"\n" +
	"GpuContext\x12#\n" +
	"\rcaptured_pids\x18\x01 \x03(\rR\fcapturedPids\x12'\n" +
	"\x0fvisible_devices\x18\x02 \x03(\tR\x0evisibleDevices\x12G\n" +
	"\n" +
	"device_map\x18\x03 \x03(\v2(.snapshot.pagebroker.v1.GpuDeviceMappingR\tdeviceMap\"M\n" +
	"\tGpuTarget\x12!\n" +
	"\fcaptured_pid\x18\x01 \x01(\rR\vcapturedPid\x12\x1d\n" +
	"\n" +
	"target_pid\x18\x02 \x01(\rR\ttargetPid\"\x91\x01\n" +
	"\x14CheckpointGpuRequest\x12;\n" +
	"\atargets\x18\x01 \x03(\v2!.snapshot.pagebroker.v1.GpuTargetR\atargets\x12<\n" +
	"\acontext\x18\x02 \x01(\v2\".snapshot.pagebroker.v1.GpuContextR\acontext\"\x8e\x01\n" +
	"\x11RestoreGpuRequest\x12;\n" +
	"\atargets\x18\x01 \x03(\v2!.snapshot.pagebroker.v1.GpuTargetR\atargets\x12<\n" +
	"\acontext\x18\x02 \x01(\v2\".snapshot.pagebroker.v1.GpuContextR\acontext\"\x15\n" +
	"\x13CapabilitiesRequest\"\x95\x01\n" +
	"\x14StagedRestoreRequest\x12>\n" +
	"\x06source\x18\x01 \x01(\v2&.snapshot.pagebroker.v1.StorageBackendR\x06source\x12=\n" +
	"\tio_engine\x18\x02 \x01(\v2 .snapshot.pagebroker.v1.IOEngineR\bioEngine\"\x95\x01\n" +
	"\x14DirectRestoreRequest\x12>\n" +
	"\x06source\x18\x01 \x01(\v2&.snapshot.pagebroker.v1.StorageBackendR\x06source\x12=\n" +
	"\tio_engine\x18\x02 \x01(\v2 .snapshot.pagebroker.v1.IOEngineR\bioEngine\"\xa9\x01\n" +
	"\x1ePrepareStagedCheckpointRequest\x12H\n" +
	"\vdestination\x18\x01 \x01(\v2&.snapshot.pagebroker.v1.StorageBackendR\vdestination\x12=\n" +
	"\tio_engine\x18\x02 \x01(\v2 .snapshot.pagebroker.v1.IOEngineR\bioEngine\"\xa9\x01\n" +
	"\x1ePrepareDirectCheckpointRequest\x12H\n" +
	"\vdestination\x18\x01 \x01(\v2&.snapshot.pagebroker.v1.StorageBackendR\vdestination\x12=\n" +
	"\tio_engine\x18\x02 \x01(\v2 .snapshot.pagebroker.v1.IOEngineR\bioEngine\"\x0f\n" +
	"\rCommitRequest\"\x0e\n" +
	"\fAbortRequest\"\x97\a\n" +
	"\aRequest\x12\"\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tH\x01R\trequestId\x88\x01\x01\x12*\n" +
	"\x0etransaction_id\x18\x02 \x01(\tH\x02R\rtransactionId\x88\x01\x01\x12U\n" +
	"\x0estaged_restore\x18\x03 \x01(\v2,.snapshot.pagebroker.v1.StagedRestoreRequestH\x00R\rstagedRestore\x12t\n" +
	"\x19prepare_staged_checkpoint\x18\x04 \x01(\v26.snapshot.pagebroker.v1.PrepareStagedCheckpointRequestH\x00R\x17prepareStagedCheckpoint\x12?\n" +
	"\x06commit\x18\x05 \x01(\v2%.snapshot.pagebroker.v1.CommitRequestH\x00R\x06commit\x12<\n" +
	"\x05abort\x18\x06 \x01(\v2$.snapshot.pagebroker.v1.AbortRequestH\x00R\x05abort\x12U\n" +
	"\x0edirect_restore\x18\a \x01(\v2,.snapshot.pagebroker.v1.DirectRestoreRequestH\x00R\rdirectRestore\x12t\n" +
	"\x19prepare_direct_checkpoint\x18\b \x01(\v26.snapshot.pagebroker.v1.PrepareDirectCheckpointRequestH\x00R\x17prepareDirectCheckpoint\x12U\n" +
	"\x0echeckpoint_gpu\x18\t \x01(\v2,.snapshot.pagebroker.v1.CheckpointGpuRequestH\x00R\rcheckpointGpu\x12L\n" +
	"\vrestore_gpu\x18\n" +
	" \x01(\v2).snapshot.pagebroker.v1.RestoreGpuRequestH\x00R\n" +
	"restoreGpu\x12Q\n" +
	"\fcapabilities\x18\v \x01(\v2+.snapshot.pagebroker.v1.CapabilitiesRequestH\x00R\fcapabilitiesB\t\n" +
	"\acommandB\r\n" +
	"\v_request_idB\x11\n" +
	"\x0f_transaction_id\"Z\n" +
	"\x16StagedRestoreDirectory\x12,\n" +
	"\x0fimage_directory\x18\x01 \x01(\tH\x00R\x0eimageDirectory\x88\x01\x01B\x12\n" +
	"\x10_image_directory\"\x14\n" +
	"\x12DirectRestoreReady\"]\n" +
	"\x19DirectCheckpointDirectory\x12,\n" +
	"\x0fimage_directory\x18\x01 \x01(\tH\x00R\x0eimageDirectory\x88\x01\x01B\x12\n" +
	"\x10_image_directory\"H\n" +
	"\fCapabilities\x128\n" +
	"\x18custom_storage_available\x18\x01 \x01(\bR\x16customStorageAvailable\"O\n" +
	"\x14GpuParticipantResult\x12!\n" +
	"\fcaptured_pid\x18\x01 \x01(\rR\vcapturedPid\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x04R\x05bytes\"_\n" +
	"\vGpuComplete\x12P\n" +
	"\fparticipants\x18\x01 \x03(\v2,.snapshot.pagebroker.v1.GpuParticipantResultR\fparticipants\"]\n" +
	"\x19StagedCheckpointDirectory\x12,\n" +
	"\x0fimage_directory\x18\x01 \x01(\tH\x00R\x0eimageDirectory\x88\x01\x01B\x12\n" +
	"\x10_image_directory\"\x10\n" +
	"\x0eCommitComplete\"\x0f\n" +
	"\rAbortComplete\"\xa1\x02\n" +
	"\aFailure\x12=\n" +
	"\x04code\x18\x01 \x01(\x0e2$.snapshot.pagebroker.v1.Failure.CodeH\x00R\x04code\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x01R\amessage\x88\x01\x01\"\xa2\x01\n" +
	"\x04Code\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fINVALID_REQUEST\x10\x01\x12\x19\n" +
	"\x15TRANSACTION_NOT_FOUND\x10\x02\x12\x18\n" +
	"\x14TRANSACTION_CONFLICT\x10\x03\x12\x18\n" +
	"\x14INSUFFICIENT_STORAGE\x10\x04\x12\x11\n" +
	"\rSTORAGE_ERROR\x10\x05\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\x06B\a\n" +
	"\x05_codeB\n" +
	"\n" +
	"\b_message\"\xa0\b\n" +
	"\bResponse\x12\"\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tH\x01R\trequestId\x88\x01\x01\x12*\n" +
	"\x0etransaction_id\x18\x02 \x01(\tH\x02R\rtransactionId\x88\x01\x01\x12j\n" +
	"\x18staged_restore_directory\x18\x03 \x01(\v2..snapshot.pagebroker.v1.StagedRestoreDirectoryH\x00R\x16stagedRestoreDirectory\x12s\n" +
	"\x1bstaged_checkpoint_directory\x18\x04 \x01(\v21.snapshot.pagebroker.v1.StagedCheckpointDirectoryH\x00R\x19stagedCheckpointDirectory\x12Q\n" +
	"\x0fcommit_complete\x18\x05 \x01(\v2&.snapshot.pagebroker.v1.CommitCompleteH\x00R\x0ecommitComplete\x12N\n" +
	"\x0eabort_complete\x18\x06 \x01(\v2%.snapshot.pagebroker.v1.AbortCompleteH\x00R\rabortComplete\x12;\n" +
	"\afailure\x18\a \x01(\v2\x1f.snapshot.pagebroker.v1.FailureH\x00R\afailure\x12^\n" +
	"\x14direct_restore_ready\x18\b \x01(\v2*.snapshot.pagebroker.v1.DirectRestoreReadyH\x00R\x12directRestoreReady\x12s\n" +
	"\x1bdirect_checkpoint_directory\x18\t \x01(\v21.snapshot.pagebroker.v1.DirectCheckpointDirectoryH\x00R\x19directCheckpointDirectory\x12]\n" +
	"\x17gpu_checkpoint_complete\x18\n" +
	" \x01(\v2#.snapshot.pagebroker.v1.GpuCompleteH\x00R\x15gpuCheckpointComplete\x12W\n" +
	"\x14gpu_restore_complete\x18\v \x01(\v2#.snapshot.pagebroker.v1.GpuCompleteH\x00R\x12gpuRestoreComplete\x12J\n" +
	"\fcapabilities\x18\f \x01(\v2$.snapshot.pagebroker.v1.CapabilitiesH\x00R\fcapabilitiesB\b\n" +
	"\x06resultB\r\n" +
	"\v_request_idB\x11\n" +
	"\x0f_transaction_id\"\x0e\n" +
	"\fNixlIOEngineB9Z7github.com/ai-dynamo/snapshot/agent/internal/pagebrokerb\x06proto3"

var (
	file_v1_pagebroker_proto_rawDescOnce sync.Once
	file_v1_pagebroker_proto_rawDescData []byte
)

func file_v1_pagebroker_proto_rawDescGZIP() []byte {
	file_v1_pagebroker_proto_rawDescOnce.Do(func() {
		file_v1_pagebroker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_pagebroker_proto_rawDesc), len(file_v1_pagebroker_proto_rawDesc)))
	})
	return file_v1_pagebroker_proto_rawDescData
}

var file_v1_pagebroker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_pagebroker_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_v1_pagebroker_proto_goTypes = []any{
	(Failure_Code)(0),                      // 0: snapshot.pagebroker.v1.Failure.Code
	(*FilesystemStorage)(nil),              // 1: snapshot.pagebroker.v1.FilesystemStorage
	(*StorageBackend)(nil),                 // 2: snapshot.pagebroker.v1.StorageBackend
	(*PosixCopyIOEngine)(nil),              // 3: snapshot.pagebroker.v1.PosixCopyIOEngine
	(*IOEngine)(nil),                       // 4: snapshot.pagebroker.v1.IOEngine
	(*GpuDeviceMapping)(nil),               // 5: snapshot.pagebroker.v1.GpuDeviceMapping
	(*GpuContext)(nil),                     // 6: snapshot.pagebroker.v1.GpuContext
	(*GpuTarget)(nil),                      // 7: snapshot.pagebroker.v1.GpuTarget
	(*CheckpointGpuRequest)(nil),           // 8: snapshot.pagebroker.v1.CheckpointGpuRequest
	(*RestoreGpuRequest)(nil),              // 9: snapshot.pagebroker.v1.RestoreGpuRequest
	(*CapabilitiesRequest)(nil),            // 10: snapshot.pagebroker.v1.CapabilitiesRequest
	(*StagedRestoreRequest)(nil),           // 11: snapshot.pagebroker.v1.StagedRestoreRequest
	(*DirectRestoreRequest)(nil),           // 12: snapshot.pagebroker.v1.DirectRestoreRequest
	(*PrepareStagedCheckpointRequest)(nil), // 13: snapshot.pagebroker.v1.PrepareStagedCheckpointRequest
	(*PrepareDirectCheckpointRequest)(nil), // 14: snapshot.pagebroker.v1.PrepareDirectCheckpointRequest
	(*CommitRequest)(nil),                  // 15: snapshot.pagebroker.v1.CommitRequest
	(*AbortRequest)(nil),                   // 16: snapshot.pagebroker.v1.AbortRequest
	(*Request)(nil),                        // 17: snapshot.pagebroker.v1.Request
	(*StagedRestoreDirectory)(nil),         // 18: snapshot.pagebroker.v1.StagedRestoreDirectory
	(*DirectRestoreReady)(nil),             // 19: snapshot.pagebroker.v1.DirectRestoreReady
	(*DirectCheckpointDirectory)(nil),      // 20: snapshot.pagebroker.v1.DirectCheckpointDirectory
	(*Capabilities)(nil),                   // 21: snapshot.pagebroker.v1.Capabilities
	(*GpuParticipantResult)(nil),           // 22: snapshot.pagebroker.v1.GpuParticipantResult
	(*GpuComplete)(nil),                    // 23: snapshot.pagebroker.v1.GpuComplete
	(*StagedCheckpointDirectory)(nil),      // 24: snapshot.pagebroker.v1.StagedCheckpointDirectory
	(*CommitComplete)(nil),                 // 25: snapshot.pagebroker.v1.CommitComplete
	(*AbortComplete)(nil),                  // 26: snapshot.pagebroker.v1.AbortComplete
	(*Failure)(nil),                        // 27: snapshot.pagebroker.v1.Failure
	(*Response)(nil),                       // 28: snapshot.pagebroker.v1.Response
	(*NixlIOEngine)(nil),                   // 29: snapshot.pagebroker.v1.NixlIOEngine
}
var file_v1_pagebroker_proto_depIdxs = []int32{
	1,  // 0: snapshot.pagebroker.v1.StorageBackend.filesystem:type_name -> snapshot.pagebroker.v1.FilesystemStorage
	3,  // 1: snapshot.pagebroker.v1.IOEngine.posix_copy:type_name -> snapshot.pagebroker.v1.PosixCopyIOEngine
	29, // 2: snapshot.pagebroker.v1.IOEngine.nixl:type_name -> snapshot.pagebroker.v1.NixlIOEngine
	5,  // 3: snapshot.pagebroker.v1.GpuContext.device_map:type_name -> snapshot.pagebroker.v1.GpuDeviceMapping
	7,  // 4: snapshot.pagebroker.v1.CheckpointGpuRequest.targets:type_name -> snapshot.pagebroker.v1.GpuTarget
	6,  // 5: snapshot.pagebroker.v1.CheckpointGpuRequest.context:type_name -> snapshot.pagebroker.v1.GpuContext
	7,  // 6: snapshot.pagebroker.v1.RestoreGpuRequest.targets:type_name -> snapshot.pagebroker.v1.GpuTarget
	6,  // 7: snapshot.pagebroker.v1.RestoreGpuRequest.context:type_name -> snapshot.pagebroker.v1.GpuContext
	2,  // 8: snapshot.pagebroker.v1.StagedRestoreRequest.source:type_name -> snapshot.pagebroker.v1.StorageBackend
	4,  // 9: snapshot.pagebroker.v1.StagedRestoreRequest.io_engine:type_name -> snapshot.pagebroker.v1.IOEngine
	2,  // 10: snapshot.pagebroker.v1.DirectRestoreRequest.source:type_name -> snapshot.pagebroker.v1.StorageBackend
	4,  // 11: snapshot.pagebroker.v1.DirectRestoreRequest.io_engine:type_name -> snapshot.pagebroker.v1.IOEngine
	2,  // 12: snapshot.pagebroker.v1.PrepareStagedCheckpointRequest.destination:type_name -> snapshot.pagebroker.v1.StorageBackend
	4,  // 13: snapshot.pagebroker.v1.PrepareStagedCheckpointRequest.io_engine:type_name -> snapshot.pagebroker.v1.IOEngine
	2,  // 14: snapshot.pagebroker.v1.PrepareDirectCheckpointRequest.destination:type_name -> snapshot.pagebroker.v1.StorageBackend
	4,  // 15: snapshot.pagebroker.v1.PrepareDirectCheckpointRequest.io_engine:type_name -> snapshot.pagebroker.v1.IOEngine
	11, // 16: snapshot.pagebroker.v1.Request.staged_restore:type_name -> snapshot.pagebroker.v1.StagedRestoreRequest
	13, // 17: snapshot.pagebroker.v1.Request.prepare_staged_checkpoint:type_name -> snapshot.pagebroker.v1.PrepareStagedCheckpointRequest
	15, // 18: snapshot.pagebroker.v1.Request.commit:type_name -> snapshot.pagebroker.v1.CommitRequest
	16, // 19: snapshot.pagebroker.v1.Request.abort:type_name -> snapshot.pagebroker.v1.AbortRequest
	12, // 20: snapshot.pagebroker.v1.Request.direct_restore:type_name -> snapshot.pagebroker.v1.DirectRestoreRequest
	14, // 21: snapshot.pagebroker.v1.Request.prepare_direct_checkpoint:type_name -> snapshot.pagebroker.v1.PrepareDirectCheckpointRequest
	8,  // 22: snapshot.pagebroker.v1.Request.checkpoint_gpu:type_name -> snapshot.pagebroker.v1.CheckpointGpuRequest
	9,  // 23: snapshot.pagebroker.v1.Request.restore_gpu:type_name -> snapshot.pagebroker.v1.RestoreGpuRequest
	10, // 24: snapshot.pagebroker.v1.Request.capabilities:type_name -> snapshot.pagebroker.v1.CapabilitiesRequest
	22, // 25: snapshot.pagebroker.v1.GpuComplete.participants:type_name -> snapshot.pagebroker.v1.GpuParticipantResult
	0,  // 26: snapshot.pagebroker.v1.Failure.code:type_name -> snapshot.pagebroker.v1.Failure.Code
	18, // 27: snapshot.pagebroker.v1.Response.staged_restore_directory:type_name -> snapshot.pagebroker.v1.StagedRestoreDirectory
	24, // 28: snapshot.pagebroker.v1.Response.staged_checkpoint_directory:type_name -> snapshot.pagebroker.v1.StagedCheckpointDirectory
	25, // 29: snapshot.pagebroker.v1.Response.commit_complete:type_name -> snapshot.pagebroker.v1.CommitComplete
	26, // 30: snapshot.pagebroker.v1.Response.abort_complete:type_name -> snapshot.pagebroker.v1.AbortComplete
	27, // 31: snapshot.pagebroker.v1.Response.failure:type_name -> snapshot.pagebroker.v1.Failure
	19, // 32: snapshot.pagebroker.v1.Response.direct_restore_ready:type_name -> snapshot.pagebroker.v1.DirectRestoreReady
	20, // 33: snapshot.pagebroker.v1.Response.direct_checkpoint_directory:type_name -> snapshot.pagebroker.v1.DirectCheckpointDirectory
	23, // 34: snapshot.pagebroker.v1.Response.gpu_checkpoint_complete:type_name -> snapshot.pagebroker.v1.GpuComplete
	23, // 35: snapshot.pagebroker.v1.Response.gpu_restore_complete:type_name -> snapshot.pagebroker.v1.GpuComplete
	21, // 36: snapshot.pagebroker.v1.Response.capabilities:type_name -> snapshot.pagebroker.v1.Capabilities
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_v1_pagebroker_proto_init() }
func file_v1_pagebroker_proto_init() {
	if File_v1_pagebroker_proto != nil {
		return
	}
	file_v1_pagebroker_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_pagebroker_proto_msgTypes[1].OneofWrappers = []any{
		(*StorageBackend_Filesystem)(nil),
	}
	file_v1_pagebroker_proto_msgTypes[3].OneofWrappers = []any{
		(*IOEngine_PosixCopy)(nil),
		(*IOEngine_Nixl)(nil),
	}
	file_v1_pagebroker_proto_msgTypes[16].OneofWrappers = []any{
		(*Request_StagedRestore)(nil),
		(*Request_PrepareStagedCheckpoint)(nil),
		(*Request_Commit)(nil),
		(*Request_Abort)(nil),
		(*Request_DirectRestore)(nil),
		(*Request_PrepareDirectCheckpoint)(nil),
		(*Request_CheckpointGpu)(nil),
		(*Request_RestoreGpu)(nil),
		(*Request_Capabilities)(nil),
	}
	file_v1_pagebroker_proto_msgTypes[17].OneofWrappers = []any{}
	file_v1_pagebroker_proto_msgTypes[19].OneofWrappers = []any{}
	file_v1_pagebroker_proto_msgTypes[23].OneofWrappers = []any{}
	file_v1_pagebroker_proto_msgTypes[26].OneofWrappers = []any{}
	file_v1_pagebroker_proto_msgTypes[27].OneofWrappers = []any{
		(*Response_StagedRestoreDirectory)(nil),
		(*Response_StagedCheckpointDirectory)(nil),
		(*Response_CommitComplete)(nil),
		(*Response_AbortComplete)(nil),
		(*Response_Failure)(nil),
		(*Response_DirectRestoreReady)(nil),
		(*Response_DirectCheckpointDirectory)(nil),
		(*Response_GpuCheckpointComplete)(nil),
		(*Response_GpuRestoreComplete)(nil),
		(*Response_Capabilities)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_pagebroker_proto_rawDesc), len(file_v1_pagebroker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_pagebroker_proto_goTypes,
		DependencyIndexes: file_v1_pagebroker_proto_depIdxs,
		EnumInfos:         file_v1_pagebroker_proto_enumTypes,
		MessageInfos:      file_v1_pagebroker_proto_msgTypes,
	}.Build()
	File_v1_pagebroker_proto = out.File
	file_v1_pagebroker_proto_goTypes = nil
	file_v1_pagebroker_proto_depIdxs = nil
}
