apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "snapshot.fullname" . }}-agent
  labels:
    {{- include "snapshot.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  selector:
    matchLabels:
      {{- include "snapshot.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: agent
  template:
    metadata:
      labels:
        {{- include "snapshot.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: agent
    spec:
      containers:
        - name: agent
          image: "{{ .Values.image.agent.repository }}:{{ .Values.image.agent.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
