// Code generated by controller-gen. DO NOT EDIT.
package v1alpha1

import runtime "k8s.io/apimachinery/pkg/runtime"

func (in *Snapshot) DeepCopyInto(out *Snapshot) {
	*out = *in
}

func (in *Snapshot) DeepCopyObject() runtime.Object {
	out := new(Snapshot)
	in.DeepCopyInto(out)
	return out
}

func (in *SnapshotList) DeepCopyInto(out *SnapshotList) {
	*out = *in
}

func (in *SnapshotList) DeepCopyObject() runtime.Object {
	out := new(SnapshotList)
	in.DeepCopyInto(out)
	return out
}

func (in *SnapshotContent) DeepCopyInto(out *SnapshotContent) {
	*out = *in
}

func (in *SnapshotContent) DeepCopyObject() runtime.Object {
	out := new(SnapshotContent)
	in.DeepCopyInto(out)
	return out
}

func (in *SnapshotContentList) DeepCopyInto(out *SnapshotContentList) {
	*out = *in
}

func (in *SnapshotContentList) DeepCopyObject() runtime.Object {
	out := new(SnapshotContentList)
	in.DeepCopyInto(out)
	return out
}

func (in *SnapshotJob) DeepCopyInto(out *SnapshotJob) {
	*out = *in
}

func (in *SnapshotJob) DeepCopyObject() runtime.Object {
	out := new(SnapshotJob)
	in.DeepCopyInto(out)
	return out
}

func (in *SnapshotJobList) DeepCopyInto(out *SnapshotJobList) {
	*out = *in
}

func (in *SnapshotJobList) DeepCopyObject() runtime.Object {
	out := new(SnapshotJobList)
	in.DeepCopyInto(out)
	return out
}
