//go:build !ignore_autogenerated

/*
SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodReference) DeepCopyInto(out *PodReference) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodReference.
func (in *PodReference) DeepCopy() *PodReference {
	if in == nil {
		return nil
	}
	out := new(PodReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSnapshot) DeepCopyInto(out *PodSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSnapshot.
func (in *PodSnapshot) DeepCopy() *PodSnapshot {
	if in == nil {
		return nil
	}
	out := new(PodSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSnapshotContent) DeepCopyInto(out *PodSnapshotContent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSnapshotContent.
func (in *PodSnapshotContent) DeepCopy() *PodSnapshotContent {
	if in == nil {
		return nil
	}
	out := new(PodSnapshotContent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodSnapshotContent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSnapshotContentList) DeepCopyInto(out *PodSnapshotContentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodSnapshotContent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSnapshotContentList.
func (in *PodSnapshotContentList) DeepCopy() *PodSnapshotContentList {
	if in == nil {
		return nil
	}
	out := new(PodSnapshotContentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodSnapshotContentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSnapshotContentSource) DeepCopyInto(out *PodSnapshotContentSource) {
	*out = *in
	in.PodRef.DeepCopyInto(&out.PodRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSnapshotContentSource.
func (in *PodSnapshotContentSource) DeepCopy() *PodSnapshotContentSource {
	if in == nil {
		return nil
	}
	out := new(PodSnapshotContentSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSnapshotContentSpec) DeepCopyInto(out *PodSnapshotContentSpec) {
	*out = *in
	out.PodSnapshotRef = in.PodSnapshotRef
	in.Source.DeepCopyInto(&out.Source)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSnapshotContentSpec.
func (in *PodSnapshotContentSpec) DeepCopy() *PodSnapshotContentSpec {
	if in == nil {
		return nil
	}
	out := new(PodSnapshotContentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSnapshotContentStatus) DeepCopyInto(out *PodSnapshotContentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSnapshotContentStatus.
func (in *PodSnapshotContentStatus) DeepCopy() *PodSnapshotContentStatus {
	if in == nil {
		return nil
	}
	out := new(PodSnapshotContentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSnapshotList) DeepCopyInto(out *PodSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSnapshotList.
func (in *PodSnapshotList) DeepCopy() *PodSnapshotList {
	if in == nil {
		return nil
	}
	out := new(PodSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSnapshotReference) DeepCopyInto(out *PodSnapshotReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSnapshotReference.
func (in *PodSnapshotReference) DeepCopy() *PodSnapshotReference {
	if in == nil {
		return nil
	}
	out := new(PodSnapshotReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSnapshotSource) DeepCopyInto(out *PodSnapshotSource) {
	*out = *in
	in.PodRef.DeepCopyInto(&out.PodRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSnapshotSource.
func (in *PodSnapshotSource) DeepCopy() *PodSnapshotSource {
	if in == nil {
		return nil
	}
	out := new(PodSnapshotSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSnapshotSpec) DeepCopyInto(out *PodSnapshotSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSnapshotSpec.
func (in *PodSnapshotSpec) DeepCopy() *PodSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(PodSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSnapshotStatus) DeepCopyInto(out *PodSnapshotStatus) {
	*out = *in
	if in.BoundPodSnapshotContentName != nil {
		in, out := &in.BoundPodSnapshotContentName, &out.BoundPodSnapshotContentName
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSnapshotStatus.
func (in *PodSnapshotStatus) DeepCopy() *PodSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(PodSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreStatusAnnotationKeys) DeepCopyInto(out *RestoreStatusAnnotationKeys) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreStatusAnnotationKeys.
func (in *RestoreStatusAnnotationKeys) DeepCopy() *RestoreStatusAnnotationKeys {
	if in == nil {
		return nil
	}
	out := new(RestoreStatusAnnotationKeys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Storage) DeepCopyInto(out *Storage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Storage.
func (in *Storage) DeepCopy() *Storage {
	if in == nil {
		return nil
	}
	out := new(Storage)
	in.DeepCopyInto(out)
	return out
}
