// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include <string>

namespace snapshot::pagebroker {

// StorageConfig is the subset of the resolved storage.yaml (written by the
// chart, read identically by the operator) PageBroker needs to configure its
// store identity. See charts/snapshot/templates/configmap.yaml for the exact
// shape this parses.
struct StorageConfig {
  std::string type;
  std::string pvc_namespace;
  std::string pvc_claim_name;
  std::string pvc_base_path;
};

// ParseStorageConfig reads the fixed four-field storage.yaml shape the chart
// emits. This is not a general YAML parser: it recognizes exactly this
// schema (a top-level "type" scalar and a "pvc" block with three scalar
// children) and throws std::runtime_error on anything else, including a
// well-formed YAML document in a shape it doesn't expect. storage.yaml is
// first-party configuration generated by this chart, not untrusted input, so
// a strict fixed-shape parser is preferable to a general YAML dependency for
// four string fields.
StorageConfig ParseStorageConfig(const std::string& yaml_text);

}  // namespace snapshot::pagebroker
